/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "s_proxy_curl.pb-c.h"
void   s_proxy_curl_json_data_rq_init
                     (s_proxy_curl_json_data_rq         *message)
{
  static s_proxy_curl_json_data_rq init_value = s_proxy_curl_json_data_rq_Init;
  *message = init_value;
}
size_t s_proxy_curl_json_data_rq_get_packed_size
                     (const s_proxy_curl_json_data_rq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &s_proxy_curl_json_data_rq_descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t s_proxy_curl_json_data_rq_pack
                     (const s_proxy_curl_json_data_rq *message,
                      unsigned char       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &s_proxy_curl_json_data_rq_descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t s_proxy_curl_json_data_rq_pack_to_buffer
                     (const s_proxy_curl_json_data_rq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &s_proxy_curl_json_data_rq_descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
s_proxy_curl_json_data_rq *
       s_proxy_curl_json_data_rq_unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const unsigned char       *data)
{
  return (s_proxy_curl_json_data_rq *)
     protobuf_c_message_unpack (&s_proxy_curl_json_data_rq_descriptor,
                                allocator, len, data);
}
void   s_proxy_curl_json_data_rq_free_unpacked
                     (s_proxy_curl_json_data_rq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &s_proxy_curl_json_data_rq_descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   s_proxy_curl_json_data_rs_init
                     (s_proxy_curl_json_data_rs         *message)
{
  static s_proxy_curl_json_data_rs init_value = s_proxy_curl_json_data_rs_Init;
  *message = init_value;
}
size_t s_proxy_curl_json_data_rs_get_packed_size
                     (const s_proxy_curl_json_data_rs *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &s_proxy_curl_json_data_rs_descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t s_proxy_curl_json_data_rs_pack
                     (const s_proxy_curl_json_data_rs *message,
                      unsigned char       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &s_proxy_curl_json_data_rs_descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t s_proxy_curl_json_data_rs_pack_to_buffer
                     (const s_proxy_curl_json_data_rs *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &s_proxy_curl_json_data_rs_descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
s_proxy_curl_json_data_rs *
       s_proxy_curl_json_data_rs_unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const unsigned char       *data)
{
  return (s_proxy_curl_json_data_rs *)
     protobuf_c_message_unpack (&s_proxy_curl_json_data_rs_descriptor,
                                allocator, len, data);
}
void   s_proxy_curl_json_data_rs_free_unpacked
                     (s_proxy_curl_json_data_rs *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &s_proxy_curl_json_data_rs_descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
const ProtobufCEnumValue s_proxy_curl_json_data_rq_msg_enum_values_by_number[1] =
{
  { "id", "s_proxy_curl_json_data_rq_msg_ID", 16777472 },
};
static const ProtobufCIntRange s_proxy_curl_json_data_rq_msg_value_ranges[] = {
{16777472, 0},{0, 1}
};
const ProtobufCEnumValueIndex s_proxy_curl_json_data_rq_msg_enum_values_by_name[1] =
{
  { "id", 0 },
};
const ProtobufCEnumDescriptor s_proxy_curl_json_data_rq_msg_descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "s_proxy_curl.json_data_rq.msg",
  "msg",
  "s_proxy_curl_json_data_rq_msg",
  "s_proxy_curl",
  1,
  s_proxy_curl_json_data_rq_msg_enum_values_by_number,
  1,
  s_proxy_curl_json_data_rq_msg_enum_values_by_name,
  1,
  s_proxy_curl_json_data_rq_msg_value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor s_proxy_curl_json_data_rq_field_descriptors[1] =
{
  {
    "buffer",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(s_proxy_curl_json_data_rq, buffer),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned s_proxy_curl_json_data_rq_field_indices_by_name[] = {
  0,   /* field[0] = buffer */
};
static const ProtobufCIntRange s_proxy_curl_json_data_rq_number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor s_proxy_curl_json_data_rq_descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "s_proxy_curl.json_data_rq",
  "JsonDataRq",
  "s_proxy_curl_json_data_rq",
  "s_proxy_curl",
  sizeof(s_proxy_curl_json_data_rq),
  1,
  s_proxy_curl_json_data_rq_field_descriptors,
  s_proxy_curl_json_data_rq_field_indices_by_name,
  1,  s_proxy_curl_json_data_rq_number_ranges,
  (ProtobufCMessageInit) s_proxy_curl_json_data_rq_init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue s_proxy_curl_json_data_rs_msg_enum_values_by_number[1] =
{
  { "id", "s_proxy_curl_json_data_rs_msg_ID", 16777473 },
};
static const ProtobufCIntRange s_proxy_curl_json_data_rs_msg_value_ranges[] = {
{16777473, 0},{0, 1}
};
const ProtobufCEnumValueIndex s_proxy_curl_json_data_rs_msg_enum_values_by_name[1] =
{
  { "id", 0 },
};
const ProtobufCEnumDescriptor s_proxy_curl_json_data_rs_msg_descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "s_proxy_curl.json_data_rs.msg",
  "msg",
  "s_proxy_curl_json_data_rs_msg",
  "s_proxy_curl",
  1,
  s_proxy_curl_json_data_rs_msg_enum_values_by_number,
  1,
  s_proxy_curl_json_data_rs_msg_enum_values_by_name,
  1,
  s_proxy_curl_json_data_rs_msg_value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const unsigned int s_proxy_curl_json_data_rs_curl_code_default_value = 0;
static const ProtobufCFieldDescriptor s_proxy_curl_json_data_rs_field_descriptors[3] =
{
  {
    "error",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(s_proxy_curl_json_data_rs, error),
    &b_error_info_descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "curl_code",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(s_proxy_curl_json_data_rs, curl_code),
    NULL,
    &s_proxy_curl_json_data_rs_curl_code_default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buffer",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(s_proxy_curl_json_data_rs, buffer),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned s_proxy_curl_json_data_rs_field_indices_by_name[] = {
  2,   /* field[2] = buffer */
  1,   /* field[1] = curl_code */
  0,   /* field[0] = error */
};
static const ProtobufCIntRange s_proxy_curl_json_data_rs_number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor s_proxy_curl_json_data_rs_descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "s_proxy_curl.json_data_rs",
  "JsonDataRs",
  "s_proxy_curl_json_data_rs",
  "s_proxy_curl",
  sizeof(s_proxy_curl_json_data_rs),
  3,
  s_proxy_curl_json_data_rs_field_descriptors,
  s_proxy_curl_json_data_rs_field_indices_by_name,
  1,  s_proxy_curl_json_data_rs_number_ranges,
  (ProtobufCMessageInit) s_proxy_curl_json_data_rs_init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue s_proxy_curl_msg_enum_values_by_number[2] =
{
  { "min_id", "s_proxy_curl_msg_MIN_ID", 16777472 },
  { "max_id", "s_proxy_curl_msg_MAX_ID", 16777727 },
};
static const ProtobufCIntRange s_proxy_curl_msg_value_ranges[] = {
{16777472, 0},{16777727, 1},{0, 2}
};
const ProtobufCEnumValueIndex s_proxy_curl_msg_enum_values_by_name[2] =
{
  { "max_id", 1 },
  { "min_id", 0 },
};
const ProtobufCEnumDescriptor s_proxy_curl_msg_descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "s_proxy_curl.msg",
  "msg",
  "s_proxy_curl_msg",
  "s_proxy_curl",
  2,
  s_proxy_curl_msg_enum_values_by_number,
  2,
  s_proxy_curl_msg_enum_values_by_name,
  2,
  s_proxy_curl_msg_value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
