// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: c_business_nt_message.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class B_error_info;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum C_business_nt_message_msg

typedef GPB_ENUM(C_business_nt_message_msg) {
  C_business_nt_message_msg_MinId = 33554432,
  C_business_nt_message_msg_MaxId = 33554687,
};

GPBEnumDescriptor *C_business_nt_message_msg_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL C_business_nt_message_msg_IsValidValue(int32_t value);

#pragma mark - Enum C_business_nt_message_nt_message_consume_by_id_rq_msg

typedef GPB_ENUM(C_business_nt_message_nt_message_consume_by_id_rq_msg) {
  C_business_nt_message_nt_message_consume_by_id_rq_msg_Id = 33554433,
};

GPBEnumDescriptor *C_business_nt_message_nt_message_consume_by_id_rq_msg_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL C_business_nt_message_nt_message_consume_by_id_rq_msg_IsValidValue(int32_t value);

#pragma mark - Enum C_business_nt_message_nt_message_consume_by_id_rs_msg

typedef GPB_ENUM(C_business_nt_message_nt_message_consume_by_id_rs_msg) {
  C_business_nt_message_nt_message_consume_by_id_rs_msg_Id = 33554434,
};

GPBEnumDescriptor *C_business_nt_message_nt_message_consume_by_id_rs_msg_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL C_business_nt_message_nt_message_consume_by_id_rs_msg_IsValidValue(int32_t value);

#pragma mark - Enum C_business_nt_message_nt_message_consume_by_maxid_rq_msg

typedef GPB_ENUM(C_business_nt_message_nt_message_consume_by_maxid_rq_msg) {
  C_business_nt_message_nt_message_consume_by_maxid_rq_msg_Id = 33554435,
};

GPBEnumDescriptor *C_business_nt_message_nt_message_consume_by_maxid_rq_msg_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL C_business_nt_message_nt_message_consume_by_maxid_rq_msg_IsValidValue(int32_t value);

#pragma mark - Enum C_business_nt_message_nt_message_consume_by_maxid_rs_msg

typedef GPB_ENUM(C_business_nt_message_nt_message_consume_by_maxid_rs_msg) {
  C_business_nt_message_nt_message_consume_by_maxid_rs_msg_Id = 33554436,
};

GPBEnumDescriptor *C_business_nt_message_nt_message_consume_by_maxid_rs_msg_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL C_business_nt_message_nt_message_consume_by_maxid_rs_msg_IsValidValue(int32_t value);

#pragma mark - Enum C_business_nt_message_nt_message_read_note_id_rq_msg

typedef GPB_ENUM(C_business_nt_message_nt_message_read_note_id_rq_msg) {
  C_business_nt_message_nt_message_read_note_id_rq_msg_Id = 33554433,
};

GPBEnumDescriptor *C_business_nt_message_nt_message_read_note_id_rq_msg_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL C_business_nt_message_nt_message_read_note_id_rq_msg_IsValidValue(int32_t value);

#pragma mark - Enum C_business_nt_message_nt_message_read_note_id_rs_msg

typedef GPB_ENUM(C_business_nt_message_nt_message_read_note_id_rs_msg) {
  C_business_nt_message_nt_message_read_note_id_rs_msg_Id = 33554434,
};

GPBEnumDescriptor *C_business_nt_message_nt_message_read_note_id_rs_msg_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL C_business_nt_message_nt_message_read_note_id_rs_msg_IsValidValue(int32_t value);

#pragma mark - Enum C_business_nt_message_nt_message_all_unread_rq_msg

typedef GPB_ENUM(C_business_nt_message_nt_message_all_unread_rq_msg) {
  C_business_nt_message_nt_message_all_unread_rq_msg_Id = 33554435,
};

GPBEnumDescriptor *C_business_nt_message_nt_message_all_unread_rq_msg_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL C_business_nt_message_nt_message_all_unread_rq_msg_IsValidValue(int32_t value);

#pragma mark - Enum C_business_nt_message_nt_message_all_unread_rs_msg

typedef GPB_ENUM(C_business_nt_message_nt_message_all_unread_rs_msg) {
  C_business_nt_message_nt_message_all_unread_rs_msg_Id = 33554436,
};

GPBEnumDescriptor *C_business_nt_message_nt_message_all_unread_rs_msg_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL C_business_nt_message_nt_message_all_unread_rs_msg_IsValidValue(int32_t value);

#pragma mark - Enum C_business_nt_message_nt_message_all_unread_nt_msg

typedef GPB_ENUM(C_business_nt_message_nt_message_all_unread_nt_msg) {
  C_business_nt_message_nt_message_all_unread_nt_msg_Id = 33554437,
};

GPBEnumDescriptor *C_business_nt_message_nt_message_all_unread_nt_msg_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL C_business_nt_message_nt_message_all_unread_nt_msg_IsValidValue(int32_t value);

#pragma mark - C_business_nt_message_CBusinessNtMessageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface C_business_nt_message_CBusinessNtMessageRoot : GPBRootObject
@end

#pragma mark - C_business_nt_message_nt_message_consume_by_id_rq

typedef GPB_ENUM(C_business_nt_message_nt_message_consume_by_id_rq_FieldNumber) {
  C_business_nt_message_nt_message_consume_by_id_rq_FieldNumber_UserId = 1,
  C_business_nt_message_nt_message_consume_by_id_rq_FieldNumber_NoteId = 2,
};

/**
 * (tcp)消费其中一条消息记录(note_id) 应答包
 **/
@interface C_business_nt_message_nt_message_consume_by_id_rq : GPBMessage

/** 用户id */
@property(nonatomic, readwrite) uint64_t userId;

@property(nonatomic, readwrite) BOOL hasUserId;
/** 消息记录(note_id) */
@property(nonatomic, readwrite) uint64_t noteId;

@property(nonatomic, readwrite) BOOL hasNoteId;
@end

#pragma mark - C_business_nt_message_nt_message_consume_by_id_rs

typedef GPB_ENUM(C_business_nt_message_nt_message_consume_by_id_rs_FieldNumber) {
  C_business_nt_message_nt_message_consume_by_id_rs_FieldNumber_Error = 1,
  C_business_nt_message_nt_message_consume_by_id_rs_FieldNumber_UserId = 2,
  C_business_nt_message_nt_message_consume_by_id_rs_FieldNumber_NoteId = 3,
};

/**
 * (tcp)消费其中一条消息记录(note_id) 应答包
 **/
@interface C_business_nt_message_nt_message_consume_by_id_rs : GPBMessage

/** error info */
@property(nonatomic, readwrite, strong, null_resettable) B_error_info *error;
/** Test to see if @c error has been set. */
@property(nonatomic, readwrite) BOOL hasError;

/** 用户id */
@property(nonatomic, readwrite) uint64_t userId;

@property(nonatomic, readwrite) BOOL hasUserId;
/** 消息记录(note_id) */
@property(nonatomic, readwrite) uint64_t noteId;

@property(nonatomic, readwrite) BOOL hasNoteId;
@end

#pragma mark - C_business_nt_message_nt_message_consume_by_maxid_rq

typedef GPB_ENUM(C_business_nt_message_nt_message_consume_by_maxid_rq_FieldNumber) {
  C_business_nt_message_nt_message_consume_by_maxid_rq_FieldNumber_UserId = 1,
  C_business_nt_message_nt_message_consume_by_maxid_rq_FieldNumber_NoteMaxid = 2,
};

/**
 * (tcp)消费最大记录(note_maxid)以内所有未读消息 应答包
 **/
@interface C_business_nt_message_nt_message_consume_by_maxid_rq : GPBMessage

/** 用户id */
@property(nonatomic, readwrite) uint64_t userId;

@property(nonatomic, readwrite) BOOL hasUserId;
/** 最大消息记录(note_maxid) */
@property(nonatomic, readwrite) uint64_t noteMaxid;

@property(nonatomic, readwrite) BOOL hasNoteMaxid;
@end

#pragma mark - C_business_nt_message_nt_message_consume_by_maxid_rs

typedef GPB_ENUM(C_business_nt_message_nt_message_consume_by_maxid_rs_FieldNumber) {
  C_business_nt_message_nt_message_consume_by_maxid_rs_FieldNumber_Error = 1,
  C_business_nt_message_nt_message_consume_by_maxid_rs_FieldNumber_UserId = 2,
  C_business_nt_message_nt_message_consume_by_maxid_rs_FieldNumber_NoteMaxid = 3,
};

/**
 * (tcp)消费最大记录(note_maxid)以内所有未读消息 应答包
 **/
@interface C_business_nt_message_nt_message_consume_by_maxid_rs : GPBMessage

/** error info */
@property(nonatomic, readwrite, strong, null_resettable) B_error_info *error;
/** Test to see if @c error has been set. */
@property(nonatomic, readwrite) BOOL hasError;

/** 用户id */
@property(nonatomic, readwrite) uint64_t userId;

@property(nonatomic, readwrite) BOOL hasUserId;
/** 最大消息记录(note_maxid) */
@property(nonatomic, readwrite) uint64_t noteMaxid;

@property(nonatomic, readwrite) BOOL hasNoteMaxid;
@end

#pragma mark - C_business_nt_message_nt_message_read_note_id_rq

typedef GPB_ENUM(C_business_nt_message_nt_message_read_note_id_rq_FieldNumber) {
  C_business_nt_message_nt_message_read_note_id_rq_FieldNumber_UserId = 1,
  C_business_nt_message_nt_message_read_note_id_rq_FieldNumber_NoteId = 2,
};

/**
 * 可选接口（主动请求服务器发回离线状态下的消息）
 * (tcp)请求阅读其中一条消息记录(note_id)，消息会以nt异步模式发回
 **/
@interface C_business_nt_message_nt_message_read_note_id_rq : GPBMessage

/** 用户id */
@property(nonatomic, readwrite) uint64_t userId;

@property(nonatomic, readwrite) BOOL hasUserId;
/** 消息记录(note_id) */
@property(nonatomic, readwrite) uint64_t noteId;

@property(nonatomic, readwrite) BOOL hasNoteId;
@end

#pragma mark - C_business_nt_message_nt_message_read_note_id_rs

typedef GPB_ENUM(C_business_nt_message_nt_message_read_note_id_rs_FieldNumber) {
  C_business_nt_message_nt_message_read_note_id_rs_FieldNumber_Error = 1,
  C_business_nt_message_nt_message_read_note_id_rs_FieldNumber_UserId = 2,
  C_business_nt_message_nt_message_read_note_id_rs_FieldNumber_NoteId = 3,
};

/**
 * (tcp)请求阅读其中一条消息记录(note_id)，消息会以nt异步模式发回
 **/
@interface C_business_nt_message_nt_message_read_note_id_rs : GPBMessage

/** error info */
@property(nonatomic, readwrite, strong, null_resettable) B_error_info *error;
/** Test to see if @c error has been set. */
@property(nonatomic, readwrite) BOOL hasError;

/** 用户id */
@property(nonatomic, readwrite) uint64_t userId;

@property(nonatomic, readwrite) BOOL hasUserId;
/** 消息记录(note_id) */
@property(nonatomic, readwrite) uint64_t noteId;

@property(nonatomic, readwrite) BOOL hasNoteId;
@end

#pragma mark - C_business_nt_message_nt_message_all_unread_rq

typedef GPB_ENUM(C_business_nt_message_nt_message_all_unread_rq_FieldNumber) {
  C_business_nt_message_nt_message_all_unread_rq_FieldNumber_UserId = 1,
};

/**
 * (tcp)请求阅读所有未读消息记录，消息会以nt异步模式发回
 **/
@interface C_business_nt_message_nt_message_all_unread_rq : GPBMessage

/** 用户id */
@property(nonatomic, readwrite) uint64_t userId;

@property(nonatomic, readwrite) BOOL hasUserId;
@end

#pragma mark - C_business_nt_message_nt_message_all_unread_rs

typedef GPB_ENUM(C_business_nt_message_nt_message_all_unread_rs_FieldNumber) {
  C_business_nt_message_nt_message_all_unread_rs_FieldNumber_Error = 1,
  C_business_nt_message_nt_message_all_unread_rs_FieldNumber_UserId = 2,
};

/**
 * (tcp)请求阅读所有未读消息记录，消息会以nt异步模式发回
 **/
@interface C_business_nt_message_nt_message_all_unread_rs : GPBMessage

/** error info */
@property(nonatomic, readwrite, strong, null_resettable) B_error_info *error;
/** Test to see if @c error has been set. */
@property(nonatomic, readwrite) BOOL hasError;

/** 用户id */
@property(nonatomic, readwrite) uint64_t userId;

@property(nonatomic, readwrite) BOOL hasUserId;
@end

#pragma mark - C_business_nt_message_nt_message_all_unread_nt

typedef GPB_ENUM(C_business_nt_message_nt_message_all_unread_nt_FieldNumber) {
  C_business_nt_message_nt_message_all_unread_nt_FieldNumber_UserId = 2,
};

/**
 * (tcp)请求阅读所有未读消息记录，消息会以nt异步模式发回
 **/
@interface C_business_nt_message_nt_message_all_unread_nt : GPBMessage

/** 用户id */
@property(nonatomic, readwrite) uint64_t userId;

@property(nonatomic, readwrite) BOOL hasUserId;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
