// Generated by the protocol buffer compiler.  DO NOT EDIT!

package protodef.nano;

@SuppressWarnings("hiding")
public interface b_business_relation {

  public static final class user_relation extends
      com.google.protobuf.nano.MessageNano {

    private static volatile user_relation[] _emptyArray;
    public static user_relation[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new user_relation[0];
          }
        }
      }
      return _emptyArray;
    }

    // required uint64 user_id = 1;
    public long userId;

    // required uint64 friend_group_id = 2;
    public long friendGroupId;

    // required uint64 friend_id = 3;
    public long friendId;

    // required string friend_remark = 4;
    public java.lang.String friendRemark;

    // required uint32 build_friend_time = 5;
    public int buildFriendTime;

    public user_relation() {
      clear();
    }

    public user_relation clear() {
      userId = 0L;
      friendGroupId = 0L;
      friendId = 0L;
      friendRemark = "";
      buildFriendTime = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeUInt64(1, this.userId);
      output.writeUInt64(2, this.friendGroupId);
      output.writeUInt64(3, this.friendId);
      output.writeString(4, this.friendRemark);
      output.writeUInt32(5, this.buildFriendTime);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(1, this.userId);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(2, this.friendGroupId);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(3, this.friendId);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(4, this.friendRemark);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt32Size(5, this.buildFriendTime);
      return size;
    }

    @Override
    public user_relation mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.userId = input.readUInt64();
            break;
          }
          case 16: {
            this.friendGroupId = input.readUInt64();
            break;
          }
          case 24: {
            this.friendId = input.readUInt64();
            break;
          }
          case 34: {
            this.friendRemark = input.readString();
            break;
          }
          case 40: {
            this.buildFriendTime = input.readUInt32();
            break;
          }
        }
      }
    }

    public static user_relation parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new user_relation(), data);
    }

    public static user_relation parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new user_relation().mergeFrom(input);
    }
  }

  public static final class user_relation_group extends
      com.google.protobuf.nano.MessageNano {

    private static volatile user_relation_group[] _emptyArray;
    public static user_relation_group[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new user_relation_group[0];
          }
        }
      }
      return _emptyArray;
    }

    // required uint64 id = 1;
    public long id;

    // required uint64 user_id = 2;
    public long userId;

    // required string friend_group = 3;
    public java.lang.String friendGroup;

    public user_relation_group() {
      clear();
    }

    public user_relation_group clear() {
      id = 0L;
      userId = 0L;
      friendGroup = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeUInt64(1, this.id);
      output.writeUInt64(2, this.userId);
      output.writeString(3, this.friendGroup);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(1, this.id);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(2, this.userId);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(3, this.friendGroup);
      return size;
    }

    @Override
    public user_relation_group mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.id = input.readUInt64();
            break;
          }
          case 16: {
            this.userId = input.readUInt64();
            break;
          }
          case 26: {
            this.friendGroup = input.readString();
            break;
          }
        }
      }
    }

    public static user_relation_group parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new user_relation_group(), data);
    }

    public static user_relation_group parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new user_relation_group().mergeFrom(input);
    }
  }

  public static final class friend_apply extends
      com.google.protobuf.nano.MessageNano {

    private static volatile friend_apply[] _emptyArray;
    public static friend_apply[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new friend_apply[0];
          }
        }
      }
      return _emptyArray;
    }

    // required uint64 user_apply_id = 1;
    public long userApplyId;

    // required string user_apply_name = 2;
    public java.lang.String userApplyName;

    // required string user_apply_nick = 3;
    public java.lang.String userApplyNick;

    // required uint32 user_apply_create_time = 4;
    public int userApplyCreateTime;

    // required string user_apply_description = 5;
    public java.lang.String userApplyDescription;

    public friend_apply() {
      clear();
    }

    public friend_apply clear() {
      userApplyId = 0L;
      userApplyName = "";
      userApplyNick = "";
      userApplyCreateTime = 0;
      userApplyDescription = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeUInt64(1, this.userApplyId);
      output.writeString(2, this.userApplyName);
      output.writeString(3, this.userApplyNick);
      output.writeUInt32(4, this.userApplyCreateTime);
      output.writeString(5, this.userApplyDescription);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(1, this.userApplyId);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(2, this.userApplyName);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(3, this.userApplyNick);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt32Size(4, this.userApplyCreateTime);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(5, this.userApplyDescription);
      return size;
    }

    @Override
    public friend_apply mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.userApplyId = input.readUInt64();
            break;
          }
          case 18: {
            this.userApplyName = input.readString();
            break;
          }
          case 26: {
            this.userApplyNick = input.readString();
            break;
          }
          case 32: {
            this.userApplyCreateTime = input.readUInt32();
            break;
          }
          case 42: {
            this.userApplyDescription = input.readString();
            break;
          }
        }
      }
    }

    public static friend_apply parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new friend_apply(), data);
    }

    public static friend_apply parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new friend_apply().mergeFrom(input);
    }
  }
}
