// Generated by the protocol buffer compiler.  DO NOT EDIT!

package protodef.nano;

@SuppressWarnings("hiding")
public interface c_business_nt_message {

  // enum msg
  public static final int min_id = 33554432;
  public static final int max_id = 33554687;

  public static final class nt_message_consume_by_id_rq extends
      com.google.protobuf.nano.MessageNano {

    // enum msg
    public static final int id = 33554433;

    private static volatile nt_message_consume_by_id_rq[] _emptyArray;
    public static nt_message_consume_by_id_rq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new nt_message_consume_by_id_rq[0];
          }
        }
      }
      return _emptyArray;
    }

    // required uint64 user_id = 1;
    public long userId;

    // required uint64 note_id = 2;
    public long noteId;

    public nt_message_consume_by_id_rq() {
      clear();
    }

    public nt_message_consume_by_id_rq clear() {
      userId = 0L;
      noteId = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeUInt64(1, this.userId);
      output.writeUInt64(2, this.noteId);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(1, this.userId);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(2, this.noteId);
      return size;
    }

    @Override
    public nt_message_consume_by_id_rq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.userId = input.readUInt64();
            break;
          }
          case 16: {
            this.noteId = input.readUInt64();
            break;
          }
        }
      }
    }

    public static nt_message_consume_by_id_rq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new nt_message_consume_by_id_rq(), data);
    }

    public static nt_message_consume_by_id_rq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new nt_message_consume_by_id_rq().mergeFrom(input);
    }
  }

  public static final class nt_message_consume_by_id_rs extends
      com.google.protobuf.nano.MessageNano {

    // enum msg
    public static final int id = 33554434;

    private static volatile nt_message_consume_by_id_rs[] _emptyArray;
    public static nt_message_consume_by_id_rs[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new nt_message_consume_by_id_rs[0];
          }
        }
      }
      return _emptyArray;
    }

    // required .b_error.info error = 1;
    public protodef.nano.b_error.info error;

    // required uint64 user_id = 2;
    public long userId;

    // required uint64 note_id = 3;
    public long noteId;

    public nt_message_consume_by_id_rs() {
      clear();
    }

    public nt_message_consume_by_id_rs clear() {
      error = null;
      userId = 0L;
      noteId = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.error != null) {
        output.writeMessage(1, this.error);
      }
      output.writeUInt64(2, this.userId);
      output.writeUInt64(3, this.noteId);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.error != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.error);
      }
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(2, this.userId);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(3, this.noteId);
      return size;
    }

    @Override
    public nt_message_consume_by_id_rs mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.error == null) {
              this.error = new protodef.nano.b_error.info();
            }
            input.readMessage(this.error);
            break;
          }
          case 16: {
            this.userId = input.readUInt64();
            break;
          }
          case 24: {
            this.noteId = input.readUInt64();
            break;
          }
        }
      }
    }

    public static nt_message_consume_by_id_rs parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new nt_message_consume_by_id_rs(), data);
    }

    public static nt_message_consume_by_id_rs parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new nt_message_consume_by_id_rs().mergeFrom(input);
    }
  }

  public static final class nt_message_consume_by_maxid_rq extends
      com.google.protobuf.nano.MessageNano {

    // enum msg
    public static final int id = 33554435;

    private static volatile nt_message_consume_by_maxid_rq[] _emptyArray;
    public static nt_message_consume_by_maxid_rq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new nt_message_consume_by_maxid_rq[0];
          }
        }
      }
      return _emptyArray;
    }

    // required uint64 user_id = 1;
    public long userId;

    // required uint64 note_maxid = 2;
    public long noteMaxid;

    public nt_message_consume_by_maxid_rq() {
      clear();
    }

    public nt_message_consume_by_maxid_rq clear() {
      userId = 0L;
      noteMaxid = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeUInt64(1, this.userId);
      output.writeUInt64(2, this.noteMaxid);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(1, this.userId);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(2, this.noteMaxid);
      return size;
    }

    @Override
    public nt_message_consume_by_maxid_rq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.userId = input.readUInt64();
            break;
          }
          case 16: {
            this.noteMaxid = input.readUInt64();
            break;
          }
        }
      }
    }

    public static nt_message_consume_by_maxid_rq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new nt_message_consume_by_maxid_rq(), data);
    }

    public static nt_message_consume_by_maxid_rq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new nt_message_consume_by_maxid_rq().mergeFrom(input);
    }
  }

  public static final class nt_message_consume_by_maxid_rs extends
      com.google.protobuf.nano.MessageNano {

    // enum msg
    public static final int id = 33554436;

    private static volatile nt_message_consume_by_maxid_rs[] _emptyArray;
    public static nt_message_consume_by_maxid_rs[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new nt_message_consume_by_maxid_rs[0];
          }
        }
      }
      return _emptyArray;
    }

    // required .b_error.info error = 1;
    public protodef.nano.b_error.info error;

    // required uint64 user_id = 2;
    public long userId;

    // required uint64 note_maxid = 3;
    public long noteMaxid;

    public nt_message_consume_by_maxid_rs() {
      clear();
    }

    public nt_message_consume_by_maxid_rs clear() {
      error = null;
      userId = 0L;
      noteMaxid = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.error != null) {
        output.writeMessage(1, this.error);
      }
      output.writeUInt64(2, this.userId);
      output.writeUInt64(3, this.noteMaxid);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.error != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.error);
      }
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(2, this.userId);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(3, this.noteMaxid);
      return size;
    }

    @Override
    public nt_message_consume_by_maxid_rs mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.error == null) {
              this.error = new protodef.nano.b_error.info();
            }
            input.readMessage(this.error);
            break;
          }
          case 16: {
            this.userId = input.readUInt64();
            break;
          }
          case 24: {
            this.noteMaxid = input.readUInt64();
            break;
          }
        }
      }
    }

    public static nt_message_consume_by_maxid_rs parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new nt_message_consume_by_maxid_rs(), data);
    }

    public static nt_message_consume_by_maxid_rs parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new nt_message_consume_by_maxid_rs().mergeFrom(input);
    }
  }

  public static final class nt_message_read_note_id_rq extends
      com.google.protobuf.nano.MessageNano {

    // enum msg
    public static final int id = 33554433;

    private static volatile nt_message_read_note_id_rq[] _emptyArray;
    public static nt_message_read_note_id_rq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new nt_message_read_note_id_rq[0];
          }
        }
      }
      return _emptyArray;
    }

    // required uint64 user_id = 1;
    public long userId;

    // required uint64 note_id = 2;
    public long noteId;

    public nt_message_read_note_id_rq() {
      clear();
    }

    public nt_message_read_note_id_rq clear() {
      userId = 0L;
      noteId = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeUInt64(1, this.userId);
      output.writeUInt64(2, this.noteId);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(1, this.userId);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(2, this.noteId);
      return size;
    }

    @Override
    public nt_message_read_note_id_rq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.userId = input.readUInt64();
            break;
          }
          case 16: {
            this.noteId = input.readUInt64();
            break;
          }
        }
      }
    }

    public static nt_message_read_note_id_rq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new nt_message_read_note_id_rq(), data);
    }

    public static nt_message_read_note_id_rq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new nt_message_read_note_id_rq().mergeFrom(input);
    }
  }

  public static final class nt_message_read_note_id_rs extends
      com.google.protobuf.nano.MessageNano {

    // enum msg
    public static final int id = 33554434;

    private static volatile nt_message_read_note_id_rs[] _emptyArray;
    public static nt_message_read_note_id_rs[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new nt_message_read_note_id_rs[0];
          }
        }
      }
      return _emptyArray;
    }

    // required .b_error.info error = 1;
    public protodef.nano.b_error.info error;

    // required uint64 user_id = 2;
    public long userId;

    // required uint64 note_id = 3;
    public long noteId;

    public nt_message_read_note_id_rs() {
      clear();
    }

    public nt_message_read_note_id_rs clear() {
      error = null;
      userId = 0L;
      noteId = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.error != null) {
        output.writeMessage(1, this.error);
      }
      output.writeUInt64(2, this.userId);
      output.writeUInt64(3, this.noteId);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.error != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.error);
      }
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(2, this.userId);
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(3, this.noteId);
      return size;
    }

    @Override
    public nt_message_read_note_id_rs mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.error == null) {
              this.error = new protodef.nano.b_error.info();
            }
            input.readMessage(this.error);
            break;
          }
          case 16: {
            this.userId = input.readUInt64();
            break;
          }
          case 24: {
            this.noteId = input.readUInt64();
            break;
          }
        }
      }
    }

    public static nt_message_read_note_id_rs parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new nt_message_read_note_id_rs(), data);
    }

    public static nt_message_read_note_id_rs parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new nt_message_read_note_id_rs().mergeFrom(input);
    }
  }

  public static final class nt_message_all_unread_rq extends
      com.google.protobuf.nano.MessageNano {

    // enum msg
    public static final int id = 33554435;

    private static volatile nt_message_all_unread_rq[] _emptyArray;
    public static nt_message_all_unread_rq[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new nt_message_all_unread_rq[0];
          }
        }
      }
      return _emptyArray;
    }

    // required uint64 user_id = 1;
    public long userId;

    public nt_message_all_unread_rq() {
      clear();
    }

    public nt_message_all_unread_rq clear() {
      userId = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeUInt64(1, this.userId);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(1, this.userId);
      return size;
    }

    @Override
    public nt_message_all_unread_rq mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.userId = input.readUInt64();
            break;
          }
        }
      }
    }

    public static nt_message_all_unread_rq parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new nt_message_all_unread_rq(), data);
    }

    public static nt_message_all_unread_rq parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new nt_message_all_unread_rq().mergeFrom(input);
    }
  }

  public static final class nt_message_all_unread_rs extends
      com.google.protobuf.nano.MessageNano {

    // enum msg
    public static final int id = 33554436;

    private static volatile nt_message_all_unread_rs[] _emptyArray;
    public static nt_message_all_unread_rs[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new nt_message_all_unread_rs[0];
          }
        }
      }
      return _emptyArray;
    }

    // required .b_error.info error = 1;
    public protodef.nano.b_error.info error;

    // required uint64 user_id = 2;
    public long userId;

    public nt_message_all_unread_rs() {
      clear();
    }

    public nt_message_all_unread_rs clear() {
      error = null;
      userId = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.error != null) {
        output.writeMessage(1, this.error);
      }
      output.writeUInt64(2, this.userId);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.error != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.error);
      }
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(2, this.userId);
      return size;
    }

    @Override
    public nt_message_all_unread_rs mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.error == null) {
              this.error = new protodef.nano.b_error.info();
            }
            input.readMessage(this.error);
            break;
          }
          case 16: {
            this.userId = input.readUInt64();
            break;
          }
        }
      }
    }

    public static nt_message_all_unread_rs parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new nt_message_all_unread_rs(), data);
    }

    public static nt_message_all_unread_rs parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new nt_message_all_unread_rs().mergeFrom(input);
    }
  }

  public static final class nt_message_all_unread_nt extends
      com.google.protobuf.nano.MessageNano {

    // enum msg
    public static final int id = 33554437;

    private static volatile nt_message_all_unread_nt[] _emptyArray;
    public static nt_message_all_unread_nt[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new nt_message_all_unread_nt[0];
          }
        }
      }
      return _emptyArray;
    }

    // required uint64 user_id = 2;
    public long userId;

    public nt_message_all_unread_nt() {
      clear();
    }

    public nt_message_all_unread_nt clear() {
      userId = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeUInt64(2, this.userId);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(2, this.userId);
      return size;
    }

    @Override
    public nt_message_all_unread_nt mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 16: {
            this.userId = input.readUInt64();
            break;
          }
        }
      }
    }

    public static nt_message_all_unread_nt parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new nt_message_all_unread_nt(), data);
    }

    public static nt_message_all_unread_nt parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new nt_message_all_unread_nt().mergeFrom(input);
    }
  }
}
