// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: c_shuttle_entry.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "c_shuttle_entry.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace c_shuttle_entry {
class knock_rqDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<knock_rq> {
} _knock_rq_default_instance_;
class knock_rsDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<knock_rs> {
} _knock_rs_default_instance_;

namespace protobuf_c_5fshuttle_5fentry_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[3];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(knock_rq, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(knock_rq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(knock_rq, native_client_version_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(knock_rq, native_source_version_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(knock_rq, coord_info_),
  0,
  1,
  2,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(knock_rs, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(knock_rs, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(knock_rs, error_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(knock_rs, addr_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(knock_rs, public_key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(knock_rs, remote_client_version_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(knock_rs, remote_source_version_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(knock_rs, remote_server_version_),
  4,
  5,
  0,
  1,
  2,
  3,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 8, sizeof(knock_rq)},
  { 11, 22, sizeof(knock_rs)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_knock_rq_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_knock_rs_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "c_shuttle_entry.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _knock_rq_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _knock_rs_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::b_error::protobuf_b_5ferror_2eproto::InitDefaults();
  ::b_math::protobuf_b_5fmath_2eproto::InitDefaults();
  ::b_network::protobuf_b_5fnetwork_2eproto::InitDefaults();
  _knock_rq_default_instance_.DefaultConstruct();
  _knock_rs_default_instance_.DefaultConstruct();
  _knock_rq_default_instance_.get_mutable()->coord_info_ = const_cast< ::b_math::coord*>(
      ::b_math::coord::internal_default_instance());
  _knock_rs_default_instance_.get_mutable()->error_ = const_cast< ::b_error::info*>(
      ::b_error::info::internal_default_instance());
  _knock_rs_default_instance_.get_mutable()->addr_ = const_cast< ::b_network::address*>(
      ::b_network::address::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\025c_shuttle_entry.proto\022\017c_shuttle_entry"
      "\032\rb_error.proto\032\014b_math.proto\032\017b_network"
      ".proto\"\201\001\n\010knock_rq\022\037\n\025native_client_ver"
      "sion\030\001 \002(\t:\000\022\037\n\025native_source_version\030\002 "
      "\002(\t:\000\022!\n\ncoord_info\030\003 \002(\0132\r.b_math.coord"
      "\"\020\n\003msg\022\t\n\002id\020\200\240\200\020\"\323\001\n\010knock_rs\022\034\n\005error"
      "\030\001 \002(\0132\r.b_error.info\022 \n\004addr\030\002 \002(\0132\022.b_"
      "network.address\022\022\n\npublic_key\030\003 \002(\014\022\037\n\025r"
      "emote_client_version\030\004 \002(\t:\000\022\037\n\025remote_s"
      "ource_version\030\005 \002(\t:\000\022\037\n\025remote_server_v"
      "ersion\030\006 \002(\t:\000\"\020\n\003msg\022\t\n\002id\020\201\240\200\020*#\n\003msg\022"
      "\r\n\006min_id\020\200\240\200\020\022\r\n\006max_id\020\377\241\200\020BZ\n\010protode"
      "fB\017c_shuttle_entryZ\030protodef/c_shuttle_e"
      "ntry\242\002\020C_shuttle_entry_\252\002\017c_shuttle_entr"
      "y"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 561);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "c_shuttle_entry.proto", &protobuf_RegisterTypes);
  ::b_error::protobuf_b_5ferror_2eproto::AddDescriptors();
  ::b_math::protobuf_b_5fmath_2eproto::AddDescriptors();
  ::b_network::protobuf_b_5fnetwork_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_c_5fshuttle_5fentry_2eproto

const ::google::protobuf::EnumDescriptor* knock_rq_msg_descriptor() {
  protobuf_c_5fshuttle_5fentry_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_c_5fshuttle_5fentry_2eproto::file_level_enum_descriptors[0];
}
bool knock_rq_msg_IsValid(int value) {
  switch (value) {
    case 33558528:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const knock_rq_msg knock_rq::id;
const knock_rq_msg knock_rq::msg_MIN;
const knock_rq_msg knock_rq::msg_MAX;
const int knock_rq::msg_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* knock_rs_msg_descriptor() {
  protobuf_c_5fshuttle_5fentry_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_c_5fshuttle_5fentry_2eproto::file_level_enum_descriptors[1];
}
bool knock_rs_msg_IsValid(int value) {
  switch (value) {
    case 33558529:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const knock_rs_msg knock_rs::id;
const knock_rs_msg knock_rs::msg_MIN;
const knock_rs_msg knock_rs::msg_MAX;
const int knock_rs::msg_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* msg_descriptor() {
  protobuf_c_5fshuttle_5fentry_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_c_5fshuttle_5fentry_2eproto::file_level_enum_descriptors[2];
}
bool msg_IsValid(int value) {
  switch (value) {
    case 33558528:
    case 33558783:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int knock_rq::kNativeClientVersionFieldNumber;
const int knock_rq::kNativeSourceVersionFieldNumber;
const int knock_rq::kCoordInfoFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

knock_rq::knock_rq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_c_5fshuttle_5fentry_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:c_shuttle_entry.knock_rq)
}
knock_rq::knock_rq(const knock_rq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  native_client_version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_native_client_version()) {
    native_client_version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.native_client_version_);
  }
  native_source_version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_native_source_version()) {
    native_source_version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.native_source_version_);
  }
  if (from.has_coord_info()) {
    coord_info_ = new ::b_math::coord(*from.coord_info_);
  } else {
    coord_info_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:c_shuttle_entry.knock_rq)
}

void knock_rq::SharedCtor() {
  _cached_size_ = 0;
  native_client_version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  native_source_version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  coord_info_ = NULL;
}

knock_rq::~knock_rq() {
  // @@protoc_insertion_point(destructor:c_shuttle_entry.knock_rq)
  SharedDtor();
}

void knock_rq::SharedDtor() {
  native_client_version_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  native_source_version_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) {
    delete coord_info_;
  }
}

void knock_rq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* knock_rq::descriptor() {
  protobuf_c_5fshuttle_5fentry_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_c_5fshuttle_5fentry_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const knock_rq& knock_rq::default_instance() {
  protobuf_c_5fshuttle_5fentry_2eproto::InitDefaults();
  return *internal_default_instance();
}

knock_rq* knock_rq::New(::google::protobuf::Arena* arena) const {
  knock_rq* n = new knock_rq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void knock_rq::Clear() {
// @@protoc_insertion_point(message_clear_start:c_shuttle_entry.knock_rq)
  if (_has_bits_[0 / 32] & 7u) {
    if (has_native_client_version()) {
      GOOGLE_DCHECK(!native_client_version_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*native_client_version_.UnsafeRawStringPointer())->clear();
    }
    if (has_native_source_version()) {
      GOOGLE_DCHECK(!native_source_version_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*native_source_version_.UnsafeRawStringPointer())->clear();
    }
    if (has_coord_info()) {
      GOOGLE_DCHECK(coord_info_ != NULL);
      coord_info_->::b_math::coord::Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool knock_rq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:c_shuttle_entry.knock_rq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string native_client_version = 1 [default = ""];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_native_client_version()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->native_client_version().data(), this->native_client_version().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "c_shuttle_entry.knock_rq.native_client_version");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string native_source_version = 2 [default = ""];
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_native_source_version()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->native_source_version().data(), this->native_source_version().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "c_shuttle_entry.knock_rq.native_source_version");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .b_math.coord coord_info = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_coord_info()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:c_shuttle_entry.knock_rq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:c_shuttle_entry.knock_rq)
  return false;
#undef DO_
}

void knock_rq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:c_shuttle_entry.knock_rq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string native_client_version = 1 [default = ""];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->native_client_version().data(), this->native_client_version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "c_shuttle_entry.knock_rq.native_client_version");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->native_client_version(), output);
  }

  // required string native_source_version = 2 [default = ""];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->native_source_version().data(), this->native_source_version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "c_shuttle_entry.knock_rq.native_source_version");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->native_source_version(), output);
  }

  // required .b_math.coord coord_info = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->coord_info_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:c_shuttle_entry.knock_rq)
}

::google::protobuf::uint8* knock_rq::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:c_shuttle_entry.knock_rq)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string native_client_version = 1 [default = ""];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->native_client_version().data(), this->native_client_version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "c_shuttle_entry.knock_rq.native_client_version");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->native_client_version(), target);
  }

  // required string native_source_version = 2 [default = ""];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->native_source_version().data(), this->native_source_version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "c_shuttle_entry.knock_rq.native_source_version");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->native_source_version(), target);
  }

  // required .b_math.coord coord_info = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *this->coord_info_, deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:c_shuttle_entry.knock_rq)
  return target;
}

size_t knock_rq::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:c_shuttle_entry.knock_rq)
  size_t total_size = 0;

  if (has_native_client_version()) {
    // required string native_client_version = 1 [default = ""];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->native_client_version());
  }

  if (has_native_source_version()) {
    // required string native_source_version = 2 [default = ""];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->native_source_version());
  }

  if (has_coord_info()) {
    // required .b_math.coord coord_info = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->coord_info_);
  }

  return total_size;
}
size_t knock_rq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:c_shuttle_entry.knock_rq)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required string native_client_version = 1 [default = ""];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->native_client_version());

    // required string native_source_version = 2 [default = ""];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->native_source_version());

    // required .b_math.coord coord_info = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->coord_info_);

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void knock_rq::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:c_shuttle_entry.knock_rq)
  GOOGLE_DCHECK_NE(&from, this);
  const knock_rq* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const knock_rq>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:c_shuttle_entry.knock_rq)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:c_shuttle_entry.knock_rq)
    MergeFrom(*source);
  }
}

void knock_rq::MergeFrom(const knock_rq& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:c_shuttle_entry.knock_rq)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_native_client_version();
      native_client_version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.native_client_version_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_native_source_version();
      native_source_version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.native_source_version_);
    }
    if (cached_has_bits & 0x00000004u) {
      mutable_coord_info()->::b_math::coord::MergeFrom(from.coord_info());
    }
  }
}

void knock_rq::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:c_shuttle_entry.knock_rq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void knock_rq::CopyFrom(const knock_rq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:c_shuttle_entry.knock_rq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool knock_rq::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  if (has_coord_info()) {
    if (!this->coord_info_->IsInitialized()) return false;
  }
  return true;
}

void knock_rq::Swap(knock_rq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void knock_rq::InternalSwap(knock_rq* other) {
  native_client_version_.Swap(&other->native_client_version_);
  native_source_version_.Swap(&other->native_source_version_);
  std::swap(coord_info_, other->coord_info_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata knock_rq::GetMetadata() const {
  protobuf_c_5fshuttle_5fentry_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_c_5fshuttle_5fentry_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// knock_rq

// required string native_client_version = 1 [default = ""];
bool knock_rq::has_native_client_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void knock_rq::set_has_native_client_version() {
  _has_bits_[0] |= 0x00000001u;
}
void knock_rq::clear_has_native_client_version() {
  _has_bits_[0] &= ~0x00000001u;
}
void knock_rq::clear_native_client_version() {
  native_client_version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_native_client_version();
}
const ::std::string& knock_rq::native_client_version() const {
  // @@protoc_insertion_point(field_get:c_shuttle_entry.knock_rq.native_client_version)
  return native_client_version_.GetNoArena();
}
void knock_rq::set_native_client_version(const ::std::string& value) {
  set_has_native_client_version();
  native_client_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:c_shuttle_entry.knock_rq.native_client_version)
}
#if LANG_CXX11
void knock_rq::set_native_client_version(::std::string&& value) {
  set_has_native_client_version();
  native_client_version_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:c_shuttle_entry.knock_rq.native_client_version)
}
#endif
void knock_rq::set_native_client_version(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_native_client_version();
  native_client_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:c_shuttle_entry.knock_rq.native_client_version)
}
void knock_rq::set_native_client_version(const char* value, size_t size) {
  set_has_native_client_version();
  native_client_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:c_shuttle_entry.knock_rq.native_client_version)
}
::std::string* knock_rq::mutable_native_client_version() {
  set_has_native_client_version();
  // @@protoc_insertion_point(field_mutable:c_shuttle_entry.knock_rq.native_client_version)
  return native_client_version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* knock_rq::release_native_client_version() {
  // @@protoc_insertion_point(field_release:c_shuttle_entry.knock_rq.native_client_version)
  clear_has_native_client_version();
  return native_client_version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void knock_rq::set_allocated_native_client_version(::std::string* native_client_version) {
  if (native_client_version != NULL) {
    set_has_native_client_version();
  } else {
    clear_has_native_client_version();
  }
  native_client_version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), native_client_version);
  // @@protoc_insertion_point(field_set_allocated:c_shuttle_entry.knock_rq.native_client_version)
}

// required string native_source_version = 2 [default = ""];
bool knock_rq::has_native_source_version() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void knock_rq::set_has_native_source_version() {
  _has_bits_[0] |= 0x00000002u;
}
void knock_rq::clear_has_native_source_version() {
  _has_bits_[0] &= ~0x00000002u;
}
void knock_rq::clear_native_source_version() {
  native_source_version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_native_source_version();
}
const ::std::string& knock_rq::native_source_version() const {
  // @@protoc_insertion_point(field_get:c_shuttle_entry.knock_rq.native_source_version)
  return native_source_version_.GetNoArena();
}
void knock_rq::set_native_source_version(const ::std::string& value) {
  set_has_native_source_version();
  native_source_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:c_shuttle_entry.knock_rq.native_source_version)
}
#if LANG_CXX11
void knock_rq::set_native_source_version(::std::string&& value) {
  set_has_native_source_version();
  native_source_version_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:c_shuttle_entry.knock_rq.native_source_version)
}
#endif
void knock_rq::set_native_source_version(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_native_source_version();
  native_source_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:c_shuttle_entry.knock_rq.native_source_version)
}
void knock_rq::set_native_source_version(const char* value, size_t size) {
  set_has_native_source_version();
  native_source_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:c_shuttle_entry.knock_rq.native_source_version)
}
::std::string* knock_rq::mutable_native_source_version() {
  set_has_native_source_version();
  // @@protoc_insertion_point(field_mutable:c_shuttle_entry.knock_rq.native_source_version)
  return native_source_version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* knock_rq::release_native_source_version() {
  // @@protoc_insertion_point(field_release:c_shuttle_entry.knock_rq.native_source_version)
  clear_has_native_source_version();
  return native_source_version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void knock_rq::set_allocated_native_source_version(::std::string* native_source_version) {
  if (native_source_version != NULL) {
    set_has_native_source_version();
  } else {
    clear_has_native_source_version();
  }
  native_source_version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), native_source_version);
  // @@protoc_insertion_point(field_set_allocated:c_shuttle_entry.knock_rq.native_source_version)
}

// required .b_math.coord coord_info = 3;
bool knock_rq::has_coord_info() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void knock_rq::set_has_coord_info() {
  _has_bits_[0] |= 0x00000004u;
}
void knock_rq::clear_has_coord_info() {
  _has_bits_[0] &= ~0x00000004u;
}
void knock_rq::clear_coord_info() {
  if (coord_info_ != NULL) coord_info_->::b_math::coord::Clear();
  clear_has_coord_info();
}
const ::b_math::coord& knock_rq::coord_info() const {
  // @@protoc_insertion_point(field_get:c_shuttle_entry.knock_rq.coord_info)
  return coord_info_ != NULL ? *coord_info_
                         : *::b_math::coord::internal_default_instance();
}
::b_math::coord* knock_rq::mutable_coord_info() {
  set_has_coord_info();
  if (coord_info_ == NULL) {
    coord_info_ = new ::b_math::coord;
  }
  // @@protoc_insertion_point(field_mutable:c_shuttle_entry.knock_rq.coord_info)
  return coord_info_;
}
::b_math::coord* knock_rq::release_coord_info() {
  // @@protoc_insertion_point(field_release:c_shuttle_entry.knock_rq.coord_info)
  clear_has_coord_info();
  ::b_math::coord* temp = coord_info_;
  coord_info_ = NULL;
  return temp;
}
void knock_rq::set_allocated_coord_info(::b_math::coord* coord_info) {
  delete coord_info_;
  coord_info_ = coord_info;
  if (coord_info) {
    set_has_coord_info();
  } else {
    clear_has_coord_info();
  }
  // @@protoc_insertion_point(field_set_allocated:c_shuttle_entry.knock_rq.coord_info)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int knock_rs::kErrorFieldNumber;
const int knock_rs::kAddrFieldNumber;
const int knock_rs::kPublicKeyFieldNumber;
const int knock_rs::kRemoteClientVersionFieldNumber;
const int knock_rs::kRemoteSourceVersionFieldNumber;
const int knock_rs::kRemoteServerVersionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

knock_rs::knock_rs()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_c_5fshuttle_5fentry_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:c_shuttle_entry.knock_rs)
}
knock_rs::knock_rs(const knock_rs& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  public_key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_public_key()) {
    public_key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.public_key_);
  }
  remote_client_version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_remote_client_version()) {
    remote_client_version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.remote_client_version_);
  }
  remote_source_version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_remote_source_version()) {
    remote_source_version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.remote_source_version_);
  }
  remote_server_version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_remote_server_version()) {
    remote_server_version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.remote_server_version_);
  }
  if (from.has_error()) {
    error_ = new ::b_error::info(*from.error_);
  } else {
    error_ = NULL;
  }
  if (from.has_addr()) {
    addr_ = new ::b_network::address(*from.addr_);
  } else {
    addr_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:c_shuttle_entry.knock_rs)
}

void knock_rs::SharedCtor() {
  _cached_size_ = 0;
  public_key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  remote_client_version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  remote_source_version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  remote_server_version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&error_, 0, reinterpret_cast<char*>(&addr_) -
    reinterpret_cast<char*>(&error_) + sizeof(addr_));
}

knock_rs::~knock_rs() {
  // @@protoc_insertion_point(destructor:c_shuttle_entry.knock_rs)
  SharedDtor();
}

void knock_rs::SharedDtor() {
  public_key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  remote_client_version_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  remote_source_version_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  remote_server_version_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) {
    delete error_;
  }
  if (this != internal_default_instance()) {
    delete addr_;
  }
}

void knock_rs::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* knock_rs::descriptor() {
  protobuf_c_5fshuttle_5fentry_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_c_5fshuttle_5fentry_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const knock_rs& knock_rs::default_instance() {
  protobuf_c_5fshuttle_5fentry_2eproto::InitDefaults();
  return *internal_default_instance();
}

knock_rs* knock_rs::New(::google::protobuf::Arena* arena) const {
  knock_rs* n = new knock_rs;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void knock_rs::Clear() {
// @@protoc_insertion_point(message_clear_start:c_shuttle_entry.knock_rs)
  if (_has_bits_[0 / 32] & 63u) {
    if (has_public_key()) {
      GOOGLE_DCHECK(!public_key_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*public_key_.UnsafeRawStringPointer())->clear();
    }
    if (has_remote_client_version()) {
      GOOGLE_DCHECK(!remote_client_version_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*remote_client_version_.UnsafeRawStringPointer())->clear();
    }
    if (has_remote_source_version()) {
      GOOGLE_DCHECK(!remote_source_version_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*remote_source_version_.UnsafeRawStringPointer())->clear();
    }
    if (has_remote_server_version()) {
      GOOGLE_DCHECK(!remote_server_version_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*remote_server_version_.UnsafeRawStringPointer())->clear();
    }
    if (has_error()) {
      GOOGLE_DCHECK(error_ != NULL);
      error_->::b_error::info::Clear();
    }
    if (has_addr()) {
      GOOGLE_DCHECK(addr_ != NULL);
      addr_->::b_network::address::Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool knock_rs::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:c_shuttle_entry.knock_rs)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .b_error.info error = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_error()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required .b_network.address addr = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_addr()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required bytes public_key = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_public_key()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string remote_client_version = 4 [default = ""];
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_remote_client_version()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->remote_client_version().data(), this->remote_client_version().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "c_shuttle_entry.knock_rs.remote_client_version");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string remote_source_version = 5 [default = ""];
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_remote_source_version()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->remote_source_version().data(), this->remote_source_version().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "c_shuttle_entry.knock_rs.remote_source_version");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string remote_server_version = 6 [default = ""];
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_remote_server_version()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->remote_server_version().data(), this->remote_server_version().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "c_shuttle_entry.knock_rs.remote_server_version");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:c_shuttle_entry.knock_rs)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:c_shuttle_entry.knock_rs)
  return false;
#undef DO_
}

void knock_rs::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:c_shuttle_entry.knock_rs)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .b_error.info error = 1;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->error_, output);
  }

  // required .b_network.address addr = 2;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->addr_, output);
  }

  // required bytes public_key = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->public_key(), output);
  }

  // required string remote_client_version = 4 [default = ""];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->remote_client_version().data(), this->remote_client_version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "c_shuttle_entry.knock_rs.remote_client_version");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->remote_client_version(), output);
  }

  // required string remote_source_version = 5 [default = ""];
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->remote_source_version().data(), this->remote_source_version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "c_shuttle_entry.knock_rs.remote_source_version");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->remote_source_version(), output);
  }

  // required string remote_server_version = 6 [default = ""];
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->remote_server_version().data(), this->remote_server_version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "c_shuttle_entry.knock_rs.remote_server_version");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->remote_server_version(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:c_shuttle_entry.knock_rs)
}

::google::protobuf::uint8* knock_rs::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:c_shuttle_entry.knock_rs)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .b_error.info error = 1;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->error_, deterministic, target);
  }

  // required .b_network.address addr = 2;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->addr_, deterministic, target);
  }

  // required bytes public_key = 3;
  if (cached_has_bits & 0x00000001u) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->public_key(), target);
  }

  // required string remote_client_version = 4 [default = ""];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->remote_client_version().data(), this->remote_client_version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "c_shuttle_entry.knock_rs.remote_client_version");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->remote_client_version(), target);
  }

  // required string remote_source_version = 5 [default = ""];
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->remote_source_version().data(), this->remote_source_version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "c_shuttle_entry.knock_rs.remote_source_version");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->remote_source_version(), target);
  }

  // required string remote_server_version = 6 [default = ""];
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->remote_server_version().data(), this->remote_server_version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "c_shuttle_entry.knock_rs.remote_server_version");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->remote_server_version(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:c_shuttle_entry.knock_rs)
  return target;
}

size_t knock_rs::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:c_shuttle_entry.knock_rs)
  size_t total_size = 0;

  if (has_public_key()) {
    // required bytes public_key = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->public_key());
  }

  if (has_remote_client_version()) {
    // required string remote_client_version = 4 [default = ""];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->remote_client_version());
  }

  if (has_remote_source_version()) {
    // required string remote_source_version = 5 [default = ""];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->remote_source_version());
  }

  if (has_remote_server_version()) {
    // required string remote_server_version = 6 [default = ""];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->remote_server_version());
  }

  if (has_error()) {
    // required .b_error.info error = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->error_);
  }

  if (has_addr()) {
    // required .b_network.address addr = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->addr_);
  }

  return total_size;
}
size_t knock_rs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:c_shuttle_entry.knock_rs)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (((_has_bits_[0] & 0x0000003f) ^ 0x0000003f) == 0) {  // All required fields are present.
    // required bytes public_key = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->public_key());

    // required string remote_client_version = 4 [default = ""];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->remote_client_version());

    // required string remote_source_version = 5 [default = ""];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->remote_source_version());

    // required string remote_server_version = 6 [default = ""];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->remote_server_version());

    // required .b_error.info error = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->error_);

    // required .b_network.address addr = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->addr_);

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void knock_rs::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:c_shuttle_entry.knock_rs)
  GOOGLE_DCHECK_NE(&from, this);
  const knock_rs* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const knock_rs>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:c_shuttle_entry.knock_rs)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:c_shuttle_entry.knock_rs)
    MergeFrom(*source);
  }
}

void knock_rs::MergeFrom(const knock_rs& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:c_shuttle_entry.knock_rs)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 63u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_public_key();
      public_key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.public_key_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_remote_client_version();
      remote_client_version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.remote_client_version_);
    }
    if (cached_has_bits & 0x00000004u) {
      set_has_remote_source_version();
      remote_source_version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.remote_source_version_);
    }
    if (cached_has_bits & 0x00000008u) {
      set_has_remote_server_version();
      remote_server_version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.remote_server_version_);
    }
    if (cached_has_bits & 0x00000010u) {
      mutable_error()->::b_error::info::MergeFrom(from.error());
    }
    if (cached_has_bits & 0x00000020u) {
      mutable_addr()->::b_network::address::MergeFrom(from.addr());
    }
  }
}

void knock_rs::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:c_shuttle_entry.knock_rs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void knock_rs::CopyFrom(const knock_rs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:c_shuttle_entry.knock_rs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool knock_rs::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000003f) != 0x0000003f) return false;
  if (has_error()) {
    if (!this->error_->IsInitialized()) return false;
  }
  if (has_addr()) {
    if (!this->addr_->IsInitialized()) return false;
  }
  return true;
}

void knock_rs::Swap(knock_rs* other) {
  if (other == this) return;
  InternalSwap(other);
}
void knock_rs::InternalSwap(knock_rs* other) {
  public_key_.Swap(&other->public_key_);
  remote_client_version_.Swap(&other->remote_client_version_);
  remote_source_version_.Swap(&other->remote_source_version_);
  remote_server_version_.Swap(&other->remote_server_version_);
  std::swap(error_, other->error_);
  std::swap(addr_, other->addr_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata knock_rs::GetMetadata() const {
  protobuf_c_5fshuttle_5fentry_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_c_5fshuttle_5fentry_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// knock_rs

// required .b_error.info error = 1;
bool knock_rs::has_error() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void knock_rs::set_has_error() {
  _has_bits_[0] |= 0x00000010u;
}
void knock_rs::clear_has_error() {
  _has_bits_[0] &= ~0x00000010u;
}
void knock_rs::clear_error() {
  if (error_ != NULL) error_->::b_error::info::Clear();
  clear_has_error();
}
const ::b_error::info& knock_rs::error() const {
  // @@protoc_insertion_point(field_get:c_shuttle_entry.knock_rs.error)
  return error_ != NULL ? *error_
                         : *::b_error::info::internal_default_instance();
}
::b_error::info* knock_rs::mutable_error() {
  set_has_error();
  if (error_ == NULL) {
    error_ = new ::b_error::info;
  }
  // @@protoc_insertion_point(field_mutable:c_shuttle_entry.knock_rs.error)
  return error_;
}
::b_error::info* knock_rs::release_error() {
  // @@protoc_insertion_point(field_release:c_shuttle_entry.knock_rs.error)
  clear_has_error();
  ::b_error::info* temp = error_;
  error_ = NULL;
  return temp;
}
void knock_rs::set_allocated_error(::b_error::info* error) {
  delete error_;
  error_ = error;
  if (error) {
    set_has_error();
  } else {
    clear_has_error();
  }
  // @@protoc_insertion_point(field_set_allocated:c_shuttle_entry.knock_rs.error)
}

// required .b_network.address addr = 2;
bool knock_rs::has_addr() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void knock_rs::set_has_addr() {
  _has_bits_[0] |= 0x00000020u;
}
void knock_rs::clear_has_addr() {
  _has_bits_[0] &= ~0x00000020u;
}
void knock_rs::clear_addr() {
  if (addr_ != NULL) addr_->::b_network::address::Clear();
  clear_has_addr();
}
const ::b_network::address& knock_rs::addr() const {
  // @@protoc_insertion_point(field_get:c_shuttle_entry.knock_rs.addr)
  return addr_ != NULL ? *addr_
                         : *::b_network::address::internal_default_instance();
}
::b_network::address* knock_rs::mutable_addr() {
  set_has_addr();
  if (addr_ == NULL) {
    addr_ = new ::b_network::address;
  }
  // @@protoc_insertion_point(field_mutable:c_shuttle_entry.knock_rs.addr)
  return addr_;
}
::b_network::address* knock_rs::release_addr() {
  // @@protoc_insertion_point(field_release:c_shuttle_entry.knock_rs.addr)
  clear_has_addr();
  ::b_network::address* temp = addr_;
  addr_ = NULL;
  return temp;
}
void knock_rs::set_allocated_addr(::b_network::address* addr) {
  delete addr_;
  addr_ = addr;
  if (addr) {
    set_has_addr();
  } else {
    clear_has_addr();
  }
  // @@protoc_insertion_point(field_set_allocated:c_shuttle_entry.knock_rs.addr)
}

// required bytes public_key = 3;
bool knock_rs::has_public_key() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void knock_rs::set_has_public_key() {
  _has_bits_[0] |= 0x00000001u;
}
void knock_rs::clear_has_public_key() {
  _has_bits_[0] &= ~0x00000001u;
}
void knock_rs::clear_public_key() {
  public_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_public_key();
}
const ::std::string& knock_rs::public_key() const {
  // @@protoc_insertion_point(field_get:c_shuttle_entry.knock_rs.public_key)
  return public_key_.GetNoArena();
}
void knock_rs::set_public_key(const ::std::string& value) {
  set_has_public_key();
  public_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:c_shuttle_entry.knock_rs.public_key)
}
#if LANG_CXX11
void knock_rs::set_public_key(::std::string&& value) {
  set_has_public_key();
  public_key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:c_shuttle_entry.knock_rs.public_key)
}
#endif
void knock_rs::set_public_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_public_key();
  public_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:c_shuttle_entry.knock_rs.public_key)
}
void knock_rs::set_public_key(const void* value, size_t size) {
  set_has_public_key();
  public_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:c_shuttle_entry.knock_rs.public_key)
}
::std::string* knock_rs::mutable_public_key() {
  set_has_public_key();
  // @@protoc_insertion_point(field_mutable:c_shuttle_entry.knock_rs.public_key)
  return public_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* knock_rs::release_public_key() {
  // @@protoc_insertion_point(field_release:c_shuttle_entry.knock_rs.public_key)
  clear_has_public_key();
  return public_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void knock_rs::set_allocated_public_key(::std::string* public_key) {
  if (public_key != NULL) {
    set_has_public_key();
  } else {
    clear_has_public_key();
  }
  public_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), public_key);
  // @@protoc_insertion_point(field_set_allocated:c_shuttle_entry.knock_rs.public_key)
}

// required string remote_client_version = 4 [default = ""];
bool knock_rs::has_remote_client_version() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void knock_rs::set_has_remote_client_version() {
  _has_bits_[0] |= 0x00000002u;
}
void knock_rs::clear_has_remote_client_version() {
  _has_bits_[0] &= ~0x00000002u;
}
void knock_rs::clear_remote_client_version() {
  remote_client_version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_remote_client_version();
}
const ::std::string& knock_rs::remote_client_version() const {
  // @@protoc_insertion_point(field_get:c_shuttle_entry.knock_rs.remote_client_version)
  return remote_client_version_.GetNoArena();
}
void knock_rs::set_remote_client_version(const ::std::string& value) {
  set_has_remote_client_version();
  remote_client_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:c_shuttle_entry.knock_rs.remote_client_version)
}
#if LANG_CXX11
void knock_rs::set_remote_client_version(::std::string&& value) {
  set_has_remote_client_version();
  remote_client_version_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:c_shuttle_entry.knock_rs.remote_client_version)
}
#endif
void knock_rs::set_remote_client_version(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_remote_client_version();
  remote_client_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:c_shuttle_entry.knock_rs.remote_client_version)
}
void knock_rs::set_remote_client_version(const char* value, size_t size) {
  set_has_remote_client_version();
  remote_client_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:c_shuttle_entry.knock_rs.remote_client_version)
}
::std::string* knock_rs::mutable_remote_client_version() {
  set_has_remote_client_version();
  // @@protoc_insertion_point(field_mutable:c_shuttle_entry.knock_rs.remote_client_version)
  return remote_client_version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* knock_rs::release_remote_client_version() {
  // @@protoc_insertion_point(field_release:c_shuttle_entry.knock_rs.remote_client_version)
  clear_has_remote_client_version();
  return remote_client_version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void knock_rs::set_allocated_remote_client_version(::std::string* remote_client_version) {
  if (remote_client_version != NULL) {
    set_has_remote_client_version();
  } else {
    clear_has_remote_client_version();
  }
  remote_client_version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), remote_client_version);
  // @@protoc_insertion_point(field_set_allocated:c_shuttle_entry.knock_rs.remote_client_version)
}

// required string remote_source_version = 5 [default = ""];
bool knock_rs::has_remote_source_version() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void knock_rs::set_has_remote_source_version() {
  _has_bits_[0] |= 0x00000004u;
}
void knock_rs::clear_has_remote_source_version() {
  _has_bits_[0] &= ~0x00000004u;
}
void knock_rs::clear_remote_source_version() {
  remote_source_version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_remote_source_version();
}
const ::std::string& knock_rs::remote_source_version() const {
  // @@protoc_insertion_point(field_get:c_shuttle_entry.knock_rs.remote_source_version)
  return remote_source_version_.GetNoArena();
}
void knock_rs::set_remote_source_version(const ::std::string& value) {
  set_has_remote_source_version();
  remote_source_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:c_shuttle_entry.knock_rs.remote_source_version)
}
#if LANG_CXX11
void knock_rs::set_remote_source_version(::std::string&& value) {
  set_has_remote_source_version();
  remote_source_version_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:c_shuttle_entry.knock_rs.remote_source_version)
}
#endif
void knock_rs::set_remote_source_version(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_remote_source_version();
  remote_source_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:c_shuttle_entry.knock_rs.remote_source_version)
}
void knock_rs::set_remote_source_version(const char* value, size_t size) {
  set_has_remote_source_version();
  remote_source_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:c_shuttle_entry.knock_rs.remote_source_version)
}
::std::string* knock_rs::mutable_remote_source_version() {
  set_has_remote_source_version();
  // @@protoc_insertion_point(field_mutable:c_shuttle_entry.knock_rs.remote_source_version)
  return remote_source_version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* knock_rs::release_remote_source_version() {
  // @@protoc_insertion_point(field_release:c_shuttle_entry.knock_rs.remote_source_version)
  clear_has_remote_source_version();
  return remote_source_version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void knock_rs::set_allocated_remote_source_version(::std::string* remote_source_version) {
  if (remote_source_version != NULL) {
    set_has_remote_source_version();
  } else {
    clear_has_remote_source_version();
  }
  remote_source_version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), remote_source_version);
  // @@protoc_insertion_point(field_set_allocated:c_shuttle_entry.knock_rs.remote_source_version)
}

// required string remote_server_version = 6 [default = ""];
bool knock_rs::has_remote_server_version() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void knock_rs::set_has_remote_server_version() {
  _has_bits_[0] |= 0x00000008u;
}
void knock_rs::clear_has_remote_server_version() {
  _has_bits_[0] &= ~0x00000008u;
}
void knock_rs::clear_remote_server_version() {
  remote_server_version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_remote_server_version();
}
const ::std::string& knock_rs::remote_server_version() const {
  // @@protoc_insertion_point(field_get:c_shuttle_entry.knock_rs.remote_server_version)
  return remote_server_version_.GetNoArena();
}
void knock_rs::set_remote_server_version(const ::std::string& value) {
  set_has_remote_server_version();
  remote_server_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:c_shuttle_entry.knock_rs.remote_server_version)
}
#if LANG_CXX11
void knock_rs::set_remote_server_version(::std::string&& value) {
  set_has_remote_server_version();
  remote_server_version_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:c_shuttle_entry.knock_rs.remote_server_version)
}
#endif
void knock_rs::set_remote_server_version(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_remote_server_version();
  remote_server_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:c_shuttle_entry.knock_rs.remote_server_version)
}
void knock_rs::set_remote_server_version(const char* value, size_t size) {
  set_has_remote_server_version();
  remote_server_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:c_shuttle_entry.knock_rs.remote_server_version)
}
::std::string* knock_rs::mutable_remote_server_version() {
  set_has_remote_server_version();
  // @@protoc_insertion_point(field_mutable:c_shuttle_entry.knock_rs.remote_server_version)
  return remote_server_version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* knock_rs::release_remote_server_version() {
  // @@protoc_insertion_point(field_release:c_shuttle_entry.knock_rs.remote_server_version)
  clear_has_remote_server_version();
  return remote_server_version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void knock_rs::set_allocated_remote_server_version(::std::string* remote_server_version) {
  if (remote_server_version != NULL) {
    set_has_remote_server_version();
  } else {
    clear_has_remote_server_version();
  }
  remote_server_version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), remote_server_version);
  // @@protoc_insertion_point(field_set_allocated:c_shuttle_entry.knock_rs.remote_server_version)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace c_shuttle_entry

// @@protoc_insertion_point(global_scope)
