// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: s_shuttle_lobby.proto

#ifndef PROTOBUF_s_5fshuttle_5flobby_2eproto__INCLUDED
#define PROTOBUF_s_5fshuttle_5flobby_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "b_math.pb.h"
// @@protoc_insertion_point(includes)
namespace b_math {
class coord;
class coordDefaultTypeInternal;
extern coordDefaultTypeInternal _coord_default_instance_;
class mat3;
class mat3DefaultTypeInternal;
extern mat3DefaultTypeInternal _mat3_default_instance_;
class mat4;
class mat4DefaultTypeInternal;
extern mat4DefaultTypeInternal _mat4_default_instance_;
class vec2;
class vec2DefaultTypeInternal;
extern vec2DefaultTypeInternal _vec2_default_instance_;
class vec3;
class vec3DefaultTypeInternal;
extern vec3DefaultTypeInternal _vec3_default_instance_;
class vec4;
class vec4DefaultTypeInternal;
extern vec4DefaultTypeInternal _vec4_default_instance_;
}  // namespace b_math
namespace s_shuttle_lobby {
class heartbeat_ev;
class heartbeat_evDefaultTypeInternal;
extern heartbeat_evDefaultTypeInternal _heartbeat_ev_default_instance_;
class token_verify_ev;
class token_verify_evDefaultTypeInternal;
extern token_verify_evDefaultTypeInternal _token_verify_ev_default_instance_;
}  // namespace s_shuttle_lobby

namespace s_shuttle_lobby {

namespace protobuf_s_5fshuttle_5flobby_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_s_5fshuttle_5flobby_2eproto

enum token_verify_ev_msg {
  token_verify_ev_msg_id = 16781569
};
bool token_verify_ev_msg_IsValid(int value);
const token_verify_ev_msg token_verify_ev_msg_msg_MIN = token_verify_ev_msg_id;
const token_verify_ev_msg token_verify_ev_msg_msg_MAX = token_verify_ev_msg_id;
const int token_verify_ev_msg_msg_ARRAYSIZE = token_verify_ev_msg_msg_MAX + 1;

const ::google::protobuf::EnumDescriptor* token_verify_ev_msg_descriptor();
inline const ::std::string& token_verify_ev_msg_Name(token_verify_ev_msg value) {
  return ::google::protobuf::internal::NameOfEnum(
    token_verify_ev_msg_descriptor(), value);
}
inline bool token_verify_ev_msg_Parse(
    const ::std::string& name, token_verify_ev_msg* value) {
  return ::google::protobuf::internal::ParseNamedEnum<token_verify_ev_msg>(
    token_verify_ev_msg_descriptor(), name, value);
}
enum heartbeat_ev_msg {
  heartbeat_ev_msg_id = 16781570
};
bool heartbeat_ev_msg_IsValid(int value);
const heartbeat_ev_msg heartbeat_ev_msg_msg_MIN = heartbeat_ev_msg_id;
const heartbeat_ev_msg heartbeat_ev_msg_msg_MAX = heartbeat_ev_msg_id;
const int heartbeat_ev_msg_msg_ARRAYSIZE = heartbeat_ev_msg_msg_MAX + 1;

const ::google::protobuf::EnumDescriptor* heartbeat_ev_msg_descriptor();
inline const ::std::string& heartbeat_ev_msg_Name(heartbeat_ev_msg value) {
  return ::google::protobuf::internal::NameOfEnum(
    heartbeat_ev_msg_descriptor(), value);
}
inline bool heartbeat_ev_msg_Parse(
    const ::std::string& name, heartbeat_ev_msg* value) {
  return ::google::protobuf::internal::ParseNamedEnum<heartbeat_ev_msg>(
    heartbeat_ev_msg_descriptor(), name, value);
}
enum msg {
  min_id = 16781568,
  max_id = 16781823
};
bool msg_IsValid(int value);
const msg msg_MIN = min_id;
const msg msg_MAX = max_id;
const int msg_ARRAYSIZE = msg_MAX + 1;

const ::google::protobuf::EnumDescriptor* msg_descriptor();
inline const ::std::string& msg_Name(msg value) {
  return ::google::protobuf::internal::NameOfEnum(
    msg_descriptor(), value);
}
inline bool msg_Parse(
    const ::std::string& name, msg* value) {
  return ::google::protobuf::internal::ParseNamedEnum<msg>(
    msg_descriptor(), name, value);
}
// ===================================================================

class token_verify_ev : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:s_shuttle_lobby.token_verify_ev) */ {
 public:
  token_verify_ev();
  virtual ~token_verify_ev();

  token_verify_ev(const token_verify_ev& from);

  inline token_verify_ev& operator=(const token_verify_ev& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const token_verify_ev& default_instance();

  static inline const token_verify_ev* internal_default_instance() {
    return reinterpret_cast<const token_verify_ev*>(
               &_token_verify_ev_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(token_verify_ev* other);

  // implements Message ----------------------------------------------

  inline token_verify_ev* New() const PROTOBUF_FINAL { return New(NULL); }

  token_verify_ev* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const token_verify_ev& from);
  void MergeFrom(const token_verify_ev& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(token_verify_ev* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef token_verify_ev_msg msg;
  static const msg id =
    token_verify_ev_msg_id;
  static inline bool msg_IsValid(int value) {
    return token_verify_ev_msg_IsValid(value);
  }
  static const msg msg_MIN =
    token_verify_ev_msg_msg_MIN;
  static const msg msg_MAX =
    token_verify_ev_msg_msg_MAX;
  static const int msg_ARRAYSIZE =
    token_verify_ev_msg_msg_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  msg_descriptor() {
    return token_verify_ev_msg_descriptor();
  }
  static inline const ::std::string& msg_Name(msg value) {
    return token_verify_ev_msg_Name(value);
  }
  static inline bool msg_Parse(const ::std::string& name,
      msg* value) {
    return token_verify_ev_msg_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required uint64 event_time = 1 [default = 0];
  bool has_event_time() const;
  void clear_event_time();
  static const int kEventTimeFieldNumber = 1;
  ::google::protobuf::uint64 event_time() const;
  void set_event_time(::google::protobuf::uint64 value);

  // required uint64 uid = 2 [default = 0];
  bool has_uid() const;
  void clear_uid();
  static const int kUidFieldNumber = 2;
  ::google::protobuf::uint64 uid() const;
  void set_uid(::google::protobuf::uint64 value);

  // required uint64 sid_now = 3 [default = 0];
  bool has_sid_now() const;
  void clear_sid_now();
  static const int kSidNowFieldNumber = 3;
  ::google::protobuf::uint64 sid_now() const;
  void set_sid_now(::google::protobuf::uint64 value);

  // required uint64 sid_old = 4 [default = 0];
  bool has_sid_old() const;
  void clear_sid_old();
  static const int kSidOldFieldNumber = 4;
  ::google::protobuf::uint64 sid_old() const;
  void set_sid_old(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:s_shuttle_lobby.token_verify_ev)
 private:
  void set_has_event_time();
  void clear_has_event_time();
  void set_has_uid();
  void clear_has_uid();
  void set_has_sid_now();
  void clear_has_sid_now();
  void set_has_sid_old();
  void clear_has_sid_old();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::uint64 event_time_;
  ::google::protobuf::uint64 uid_;
  ::google::protobuf::uint64 sid_now_;
  ::google::protobuf::uint64 sid_old_;
  friend struct protobuf_s_5fshuttle_5flobby_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class heartbeat_ev : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:s_shuttle_lobby.heartbeat_ev) */ {
 public:
  heartbeat_ev();
  virtual ~heartbeat_ev();

  heartbeat_ev(const heartbeat_ev& from);

  inline heartbeat_ev& operator=(const heartbeat_ev& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const heartbeat_ev& default_instance();

  static inline const heartbeat_ev* internal_default_instance() {
    return reinterpret_cast<const heartbeat_ev*>(
               &_heartbeat_ev_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(heartbeat_ev* other);

  // implements Message ----------------------------------------------

  inline heartbeat_ev* New() const PROTOBUF_FINAL { return New(NULL); }

  heartbeat_ev* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const heartbeat_ev& from);
  void MergeFrom(const heartbeat_ev& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(heartbeat_ev* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef heartbeat_ev_msg msg;
  static const msg id =
    heartbeat_ev_msg_id;
  static inline bool msg_IsValid(int value) {
    return heartbeat_ev_msg_IsValid(value);
  }
  static const msg msg_MIN =
    heartbeat_ev_msg_msg_MIN;
  static const msg msg_MAX =
    heartbeat_ev_msg_msg_MAX;
  static const int msg_ARRAYSIZE =
    heartbeat_ev_msg_msg_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  msg_descriptor() {
    return heartbeat_ev_msg_descriptor();
  }
  static inline const ::std::string& msg_Name(msg value) {
    return heartbeat_ev_msg_Name(value);
  }
  static inline bool msg_Parse(const ::std::string& name,
      msg* value) {
    return heartbeat_ev_msg_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .b_math.coord coord_info = 4;
  bool has_coord_info() const;
  void clear_coord_info();
  static const int kCoordInfoFieldNumber = 4;
  const ::b_math::coord& coord_info() const;
  ::b_math::coord* mutable_coord_info();
  ::b_math::coord* release_coord_info();
  void set_allocated_coord_info(::b_math::coord* coord_info);

  // required uint64 event_time = 1 [default = 0];
  bool has_event_time() const;
  void clear_event_time();
  static const int kEventTimeFieldNumber = 1;
  ::google::protobuf::uint64 event_time() const;
  void set_event_time(::google::protobuf::uint64 value);

  // required uint64 uid = 2 [default = 0];
  bool has_uid() const;
  void clear_uid();
  static const int kUidFieldNumber = 2;
  ::google::protobuf::uint64 uid() const;
  void set_uid(::google::protobuf::uint64 value);

  // required uint64 timecode_native = 3 [default = 0];
  bool has_timecode_native() const;
  void clear_timecode_native();
  static const int kTimecodeNativeFieldNumber = 3;
  ::google::protobuf::uint64 timecode_native() const;
  void set_timecode_native(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:s_shuttle_lobby.heartbeat_ev)
 private:
  void set_has_event_time();
  void clear_has_event_time();
  void set_has_uid();
  void clear_has_uid();
  void set_has_timecode_native();
  void clear_has_timecode_native();
  void set_has_coord_info();
  void clear_has_coord_info();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::b_math::coord* coord_info_;
  ::google::protobuf::uint64 event_time_;
  ::google::protobuf::uint64 uid_;
  ::google::protobuf::uint64 timecode_native_;
  friend struct protobuf_s_5fshuttle_5flobby_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// token_verify_ev

// required uint64 event_time = 1 [default = 0];
inline bool token_verify_ev::has_event_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void token_verify_ev::set_has_event_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void token_verify_ev::clear_has_event_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void token_verify_ev::clear_event_time() {
  event_time_ = GOOGLE_ULONGLONG(0);
  clear_has_event_time();
}
inline ::google::protobuf::uint64 token_verify_ev::event_time() const {
  // @@protoc_insertion_point(field_get:s_shuttle_lobby.token_verify_ev.event_time)
  return event_time_;
}
inline void token_verify_ev::set_event_time(::google::protobuf::uint64 value) {
  set_has_event_time();
  event_time_ = value;
  // @@protoc_insertion_point(field_set:s_shuttle_lobby.token_verify_ev.event_time)
}

// required uint64 uid = 2 [default = 0];
inline bool token_verify_ev::has_uid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void token_verify_ev::set_has_uid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void token_verify_ev::clear_has_uid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void token_verify_ev::clear_uid() {
  uid_ = GOOGLE_ULONGLONG(0);
  clear_has_uid();
}
inline ::google::protobuf::uint64 token_verify_ev::uid() const {
  // @@protoc_insertion_point(field_get:s_shuttle_lobby.token_verify_ev.uid)
  return uid_;
}
inline void token_verify_ev::set_uid(::google::protobuf::uint64 value) {
  set_has_uid();
  uid_ = value;
  // @@protoc_insertion_point(field_set:s_shuttle_lobby.token_verify_ev.uid)
}

// required uint64 sid_now = 3 [default = 0];
inline bool token_verify_ev::has_sid_now() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void token_verify_ev::set_has_sid_now() {
  _has_bits_[0] |= 0x00000004u;
}
inline void token_verify_ev::clear_has_sid_now() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void token_verify_ev::clear_sid_now() {
  sid_now_ = GOOGLE_ULONGLONG(0);
  clear_has_sid_now();
}
inline ::google::protobuf::uint64 token_verify_ev::sid_now() const {
  // @@protoc_insertion_point(field_get:s_shuttle_lobby.token_verify_ev.sid_now)
  return sid_now_;
}
inline void token_verify_ev::set_sid_now(::google::protobuf::uint64 value) {
  set_has_sid_now();
  sid_now_ = value;
  // @@protoc_insertion_point(field_set:s_shuttle_lobby.token_verify_ev.sid_now)
}

// required uint64 sid_old = 4 [default = 0];
inline bool token_verify_ev::has_sid_old() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void token_verify_ev::set_has_sid_old() {
  _has_bits_[0] |= 0x00000008u;
}
inline void token_verify_ev::clear_has_sid_old() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void token_verify_ev::clear_sid_old() {
  sid_old_ = GOOGLE_ULONGLONG(0);
  clear_has_sid_old();
}
inline ::google::protobuf::uint64 token_verify_ev::sid_old() const {
  // @@protoc_insertion_point(field_get:s_shuttle_lobby.token_verify_ev.sid_old)
  return sid_old_;
}
inline void token_verify_ev::set_sid_old(::google::protobuf::uint64 value) {
  set_has_sid_old();
  sid_old_ = value;
  // @@protoc_insertion_point(field_set:s_shuttle_lobby.token_verify_ev.sid_old)
}

// -------------------------------------------------------------------

// heartbeat_ev

// required uint64 event_time = 1 [default = 0];
inline bool heartbeat_ev::has_event_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void heartbeat_ev::set_has_event_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void heartbeat_ev::clear_has_event_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void heartbeat_ev::clear_event_time() {
  event_time_ = GOOGLE_ULONGLONG(0);
  clear_has_event_time();
}
inline ::google::protobuf::uint64 heartbeat_ev::event_time() const {
  // @@protoc_insertion_point(field_get:s_shuttle_lobby.heartbeat_ev.event_time)
  return event_time_;
}
inline void heartbeat_ev::set_event_time(::google::protobuf::uint64 value) {
  set_has_event_time();
  event_time_ = value;
  // @@protoc_insertion_point(field_set:s_shuttle_lobby.heartbeat_ev.event_time)
}

// required uint64 uid = 2 [default = 0];
inline bool heartbeat_ev::has_uid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void heartbeat_ev::set_has_uid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void heartbeat_ev::clear_has_uid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void heartbeat_ev::clear_uid() {
  uid_ = GOOGLE_ULONGLONG(0);
  clear_has_uid();
}
inline ::google::protobuf::uint64 heartbeat_ev::uid() const {
  // @@protoc_insertion_point(field_get:s_shuttle_lobby.heartbeat_ev.uid)
  return uid_;
}
inline void heartbeat_ev::set_uid(::google::protobuf::uint64 value) {
  set_has_uid();
  uid_ = value;
  // @@protoc_insertion_point(field_set:s_shuttle_lobby.heartbeat_ev.uid)
}

// required uint64 timecode_native = 3 [default = 0];
inline bool heartbeat_ev::has_timecode_native() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void heartbeat_ev::set_has_timecode_native() {
  _has_bits_[0] |= 0x00000008u;
}
inline void heartbeat_ev::clear_has_timecode_native() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void heartbeat_ev::clear_timecode_native() {
  timecode_native_ = GOOGLE_ULONGLONG(0);
  clear_has_timecode_native();
}
inline ::google::protobuf::uint64 heartbeat_ev::timecode_native() const {
  // @@protoc_insertion_point(field_get:s_shuttle_lobby.heartbeat_ev.timecode_native)
  return timecode_native_;
}
inline void heartbeat_ev::set_timecode_native(::google::protobuf::uint64 value) {
  set_has_timecode_native();
  timecode_native_ = value;
  // @@protoc_insertion_point(field_set:s_shuttle_lobby.heartbeat_ev.timecode_native)
}

// required .b_math.coord coord_info = 4;
inline bool heartbeat_ev::has_coord_info() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void heartbeat_ev::set_has_coord_info() {
  _has_bits_[0] |= 0x00000001u;
}
inline void heartbeat_ev::clear_has_coord_info() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void heartbeat_ev::clear_coord_info() {
  if (coord_info_ != NULL) coord_info_->::b_math::coord::Clear();
  clear_has_coord_info();
}
inline const ::b_math::coord& heartbeat_ev::coord_info() const {
  // @@protoc_insertion_point(field_get:s_shuttle_lobby.heartbeat_ev.coord_info)
  return coord_info_ != NULL ? *coord_info_
                         : *::b_math::coord::internal_default_instance();
}
inline ::b_math::coord* heartbeat_ev::mutable_coord_info() {
  set_has_coord_info();
  if (coord_info_ == NULL) {
    coord_info_ = new ::b_math::coord;
  }
  // @@protoc_insertion_point(field_mutable:s_shuttle_lobby.heartbeat_ev.coord_info)
  return coord_info_;
}
inline ::b_math::coord* heartbeat_ev::release_coord_info() {
  // @@protoc_insertion_point(field_release:s_shuttle_lobby.heartbeat_ev.coord_info)
  clear_has_coord_info();
  ::b_math::coord* temp = coord_info_;
  coord_info_ = NULL;
  return temp;
}
inline void heartbeat_ev::set_allocated_coord_info(::b_math::coord* coord_info) {
  delete coord_info_;
  coord_info_ = coord_info;
  if (coord_info) {
    set_has_coord_info();
  } else {
    clear_has_coord_info();
  }
  // @@protoc_insertion_point(field_set_allocated:s_shuttle_lobby.heartbeat_ev.coord_info)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace s_shuttle_lobby

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::s_shuttle_lobby::token_verify_ev_msg> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::s_shuttle_lobby::token_verify_ev_msg>() {
  return ::s_shuttle_lobby::token_verify_ev_msg_descriptor();
}
template <> struct is_proto_enum< ::s_shuttle_lobby::heartbeat_ev_msg> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::s_shuttle_lobby::heartbeat_ev_msg>() {
  return ::s_shuttle_lobby::heartbeat_ev_msg_descriptor();
}
template <> struct is_proto_enum< ::s_shuttle_lobby::msg> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::s_shuttle_lobby::msg>() {
  return ::s_shuttle_lobby::msg_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_s_5fshuttle_5flobby_2eproto__INCLUDED
