// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: c_basic_frame_reflex.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "CBasicFrameReflex.pbobjc.h"
 #import "BError.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - C_basic_frame_reflex_CBasicFrameReflexRoot

@implementation C_basic_frame_reflex_CBasicFrameReflexRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - C_basic_frame_reflex_CBasicFrameReflexRoot_FileDescriptor

static GPBFileDescriptor *C_basic_frame_reflex_CBasicFrameReflexRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"c_basic_frame_reflex"
                                                 objcPrefix:@"C_basic_frame_reflex_"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - Enum C_basic_frame_reflex_msg

GPBEnumDescriptor *C_basic_frame_reflex_msg_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "MinId\000MaxId\000";
    static const int32_t values[] = {
        C_basic_frame_reflex_msg_MinId,
        C_basic_frame_reflex_msg_MaxId,
    };
    static const char *extraTextFormatInfo = "\002\000#\242\000\001#\242\000";
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(C_basic_frame_reflex_msg)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:C_basic_frame_reflex_msg_IsValidValue
                              extraTextFormatInfo:extraTextFormatInfo];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL C_basic_frame_reflex_msg_IsValidValue(int32_t value__) {
  switch (value__) {
    case C_basic_frame_reflex_msg_MinId:
    case C_basic_frame_reflex_msg_MaxId:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - C_basic_frame_reflex_simulation_variable

@implementation C_basic_frame_reflex_simulation_variable

@dynamic hasUid, uid;
@dynamic commandsArray, commandsArray_Count;

typedef struct C_basic_frame_reflex_simulation_variable__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *commandsArray;
  uint64_t uid;
} C_basic_frame_reflex_simulation_variable__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "uid",
        .dataTypeSpecific.className = NULL,
        .number = C_basic_frame_reflex_simulation_variable_FieldNumber_Uid,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(C_basic_frame_reflex_simulation_variable__storage_, uid),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldHasDefaultValue),
        .dataType = GPBDataTypeUInt64,
      },
      {
        .name = "commandsArray",
        .dataTypeSpecific.className = NULL,
        .number = C_basic_frame_reflex_simulation_variable_FieldNumber_CommandsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(C_basic_frame_reflex_simulation_variable__storage_, commandsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[C_basic_frame_reflex_simulation_variable class]
                                     rootClass:[C_basic_frame_reflex_CBasicFrameReflexRoot class]
                                          file:C_basic_frame_reflex_CBasicFrameReflexRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(C_basic_frame_reflex_simulation_variable__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - C_basic_frame_reflex_simulation_frame

@implementation C_basic_frame_reflex_simulation_frame

@dynamic hasFrameNumber, frameNumber;
@dynamic variablesArray, variablesArray_Count;

typedef struct C_basic_frame_reflex_simulation_frame__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *variablesArray;
  uint64_t frameNumber;
} C_basic_frame_reflex_simulation_frame__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "frameNumber",
        .dataTypeSpecific.className = NULL,
        .number = C_basic_frame_reflex_simulation_frame_FieldNumber_FrameNumber,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(C_basic_frame_reflex_simulation_frame__storage_, frameNumber),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldHasDefaultValue),
        .dataType = GPBDataTypeUInt64,
      },
      {
        .name = "variablesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(C_basic_frame_reflex_simulation_variable),
        .number = C_basic_frame_reflex_simulation_frame_FieldNumber_VariablesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(C_basic_frame_reflex_simulation_frame__storage_, variablesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[C_basic_frame_reflex_simulation_frame class]
                                     rootClass:[C_basic_frame_reflex_CBasicFrameReflexRoot class]
                                          file:C_basic_frame_reflex_CBasicFrameReflexRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(C_basic_frame_reflex_simulation_frame__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - C_basic_frame_reflex_alloc_channel_rq

@implementation C_basic_frame_reflex_alloc_channel_rq


typedef struct C_basic_frame_reflex_alloc_channel_rq__storage_ {
  uint32_t _has_storage_[1];
} C_basic_frame_reflex_alloc_channel_rq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[C_basic_frame_reflex_alloc_channel_rq class]
                                     rootClass:[C_basic_frame_reflex_CBasicFrameReflexRoot class]
                                          file:C_basic_frame_reflex_CBasicFrameReflexRoot_FileDescriptor()
                                        fields:NULL
                                    fieldCount:0
                                   storageSize:sizeof(C_basic_frame_reflex_alloc_channel_rq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum C_basic_frame_reflex_alloc_channel_rq_msg

GPBEnumDescriptor *C_basic_frame_reflex_alloc_channel_rq_msg_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Id\000";
    static const int32_t values[] = {
        C_basic_frame_reflex_alloc_channel_rq_msg_Id,
    };
    static const char *extraTextFormatInfo = "\001\000\"\000";
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(C_basic_frame_reflex_alloc_channel_rq_msg)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:C_basic_frame_reflex_alloc_channel_rq_msg_IsValidValue
                              extraTextFormatInfo:extraTextFormatInfo];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL C_basic_frame_reflex_alloc_channel_rq_msg_IsValidValue(int32_t value__) {
  switch (value__) {
    case C_basic_frame_reflex_alloc_channel_rq_msg_Id:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - C_basic_frame_reflex_alloc_channel_rs

@implementation C_basic_frame_reflex_alloc_channel_rs

@dynamic hasError, error;

typedef struct C_basic_frame_reflex_alloc_channel_rs__storage_ {
  uint32_t _has_storage_[1];
  B_error_info *error;
} C_basic_frame_reflex_alloc_channel_rs__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "error",
        .dataTypeSpecific.className = GPBStringifySymbol(B_error_info),
        .number = C_basic_frame_reflex_alloc_channel_rs_FieldNumber_Error,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(C_basic_frame_reflex_alloc_channel_rs__storage_, error),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[C_basic_frame_reflex_alloc_channel_rs class]
                                     rootClass:[C_basic_frame_reflex_CBasicFrameReflexRoot class]
                                          file:C_basic_frame_reflex_CBasicFrameReflexRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(C_basic_frame_reflex_alloc_channel_rs__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum C_basic_frame_reflex_alloc_channel_rs_msg

GPBEnumDescriptor *C_basic_frame_reflex_alloc_channel_rs_msg_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Id\000";
    static const int32_t values[] = {
        C_basic_frame_reflex_alloc_channel_rs_msg_Id,
    };
    static const char *extraTextFormatInfo = "\001\000\"\000";
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(C_basic_frame_reflex_alloc_channel_rs_msg)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:C_basic_frame_reflex_alloc_channel_rs_msg_IsValidValue
                              extraTextFormatInfo:extraTextFormatInfo];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL C_basic_frame_reflex_alloc_channel_rs_msg_IsValidValue(int32_t value__) {
  switch (value__) {
    case C_basic_frame_reflex_alloc_channel_rs_msg_Id:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - C_basic_frame_reflex_relax_channel_rq

@implementation C_basic_frame_reflex_relax_channel_rq


typedef struct C_basic_frame_reflex_relax_channel_rq__storage_ {
  uint32_t _has_storage_[1];
} C_basic_frame_reflex_relax_channel_rq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[C_basic_frame_reflex_relax_channel_rq class]
                                     rootClass:[C_basic_frame_reflex_CBasicFrameReflexRoot class]
                                          file:C_basic_frame_reflex_CBasicFrameReflexRoot_FileDescriptor()
                                        fields:NULL
                                    fieldCount:0
                                   storageSize:sizeof(C_basic_frame_reflex_relax_channel_rq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum C_basic_frame_reflex_relax_channel_rq_msg

GPBEnumDescriptor *C_basic_frame_reflex_relax_channel_rq_msg_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Id\000";
    static const int32_t values[] = {
        C_basic_frame_reflex_relax_channel_rq_msg_Id,
    };
    static const char *extraTextFormatInfo = "\001\000\"\000";
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(C_basic_frame_reflex_relax_channel_rq_msg)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:C_basic_frame_reflex_relax_channel_rq_msg_IsValidValue
                              extraTextFormatInfo:extraTextFormatInfo];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL C_basic_frame_reflex_relax_channel_rq_msg_IsValidValue(int32_t value__) {
  switch (value__) {
    case C_basic_frame_reflex_relax_channel_rq_msg_Id:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - C_basic_frame_reflex_relax_channel_rs

@implementation C_basic_frame_reflex_relax_channel_rs

@dynamic hasError, error;

typedef struct C_basic_frame_reflex_relax_channel_rs__storage_ {
  uint32_t _has_storage_[1];
  B_error_info *error;
} C_basic_frame_reflex_relax_channel_rs__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "error",
        .dataTypeSpecific.className = GPBStringifySymbol(B_error_info),
        .number = C_basic_frame_reflex_relax_channel_rs_FieldNumber_Error,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(C_basic_frame_reflex_relax_channel_rs__storage_, error),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[C_basic_frame_reflex_relax_channel_rs class]
                                     rootClass:[C_basic_frame_reflex_CBasicFrameReflexRoot class]
                                          file:C_basic_frame_reflex_CBasicFrameReflexRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(C_basic_frame_reflex_relax_channel_rs__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum C_basic_frame_reflex_relax_channel_rs_msg

GPBEnumDescriptor *C_basic_frame_reflex_relax_channel_rs_msg_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Id\000";
    static const int32_t values[] = {
        C_basic_frame_reflex_relax_channel_rs_msg_Id,
    };
    static const char *extraTextFormatInfo = "\001\000\"\000";
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(C_basic_frame_reflex_relax_channel_rs_msg)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:C_basic_frame_reflex_relax_channel_rs_msg_IsValidValue
                              extraTextFormatInfo:extraTextFormatInfo];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL C_basic_frame_reflex_relax_channel_rs_msg_IsValidValue(int32_t value__) {
  switch (value__) {
    case C_basic_frame_reflex_relax_channel_rs_msg_Id:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - C_basic_frame_reflex_enter_channel_rq

@implementation C_basic_frame_reflex_enter_channel_rq


typedef struct C_basic_frame_reflex_enter_channel_rq__storage_ {
  uint32_t _has_storage_[1];
} C_basic_frame_reflex_enter_channel_rq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[C_basic_frame_reflex_enter_channel_rq class]
                                     rootClass:[C_basic_frame_reflex_CBasicFrameReflexRoot class]
                                          file:C_basic_frame_reflex_CBasicFrameReflexRoot_FileDescriptor()
                                        fields:NULL
                                    fieldCount:0
                                   storageSize:sizeof(C_basic_frame_reflex_enter_channel_rq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum C_basic_frame_reflex_enter_channel_rq_msg

GPBEnumDescriptor *C_basic_frame_reflex_enter_channel_rq_msg_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Id\000";
    static const int32_t values[] = {
        C_basic_frame_reflex_enter_channel_rq_msg_Id,
    };
    static const char *extraTextFormatInfo = "\001\000\"\000";
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(C_basic_frame_reflex_enter_channel_rq_msg)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:C_basic_frame_reflex_enter_channel_rq_msg_IsValidValue
                              extraTextFormatInfo:extraTextFormatInfo];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL C_basic_frame_reflex_enter_channel_rq_msg_IsValidValue(int32_t value__) {
  switch (value__) {
    case C_basic_frame_reflex_enter_channel_rq_msg_Id:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - C_basic_frame_reflex_enter_channel_rs

@implementation C_basic_frame_reflex_enter_channel_rs

@dynamic hasError, error;

typedef struct C_basic_frame_reflex_enter_channel_rs__storage_ {
  uint32_t _has_storage_[1];
  B_error_info *error;
} C_basic_frame_reflex_enter_channel_rs__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "error",
        .dataTypeSpecific.className = GPBStringifySymbol(B_error_info),
        .number = C_basic_frame_reflex_enter_channel_rs_FieldNumber_Error,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(C_basic_frame_reflex_enter_channel_rs__storage_, error),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[C_basic_frame_reflex_enter_channel_rs class]
                                     rootClass:[C_basic_frame_reflex_CBasicFrameReflexRoot class]
                                          file:C_basic_frame_reflex_CBasicFrameReflexRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(C_basic_frame_reflex_enter_channel_rs__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum C_basic_frame_reflex_enter_channel_rs_msg

GPBEnumDescriptor *C_basic_frame_reflex_enter_channel_rs_msg_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Id\000";
    static const int32_t values[] = {
        C_basic_frame_reflex_enter_channel_rs_msg_Id,
    };
    static const char *extraTextFormatInfo = "\001\000\"\000";
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(C_basic_frame_reflex_enter_channel_rs_msg)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:C_basic_frame_reflex_enter_channel_rs_msg_IsValidValue
                              extraTextFormatInfo:extraTextFormatInfo];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL C_basic_frame_reflex_enter_channel_rs_msg_IsValidValue(int32_t value__) {
  switch (value__) {
    case C_basic_frame_reflex_enter_channel_rs_msg_Id:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - C_basic_frame_reflex_leave_channel_rq

@implementation C_basic_frame_reflex_leave_channel_rq


typedef struct C_basic_frame_reflex_leave_channel_rq__storage_ {
  uint32_t _has_storage_[1];
} C_basic_frame_reflex_leave_channel_rq__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[C_basic_frame_reflex_leave_channel_rq class]
                                     rootClass:[C_basic_frame_reflex_CBasicFrameReflexRoot class]
                                          file:C_basic_frame_reflex_CBasicFrameReflexRoot_FileDescriptor()
                                        fields:NULL
                                    fieldCount:0
                                   storageSize:sizeof(C_basic_frame_reflex_leave_channel_rq__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum C_basic_frame_reflex_leave_channel_rq_msg

GPBEnumDescriptor *C_basic_frame_reflex_leave_channel_rq_msg_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Id\000";
    static const int32_t values[] = {
        C_basic_frame_reflex_leave_channel_rq_msg_Id,
    };
    static const char *extraTextFormatInfo = "\001\000\"\000";
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(C_basic_frame_reflex_leave_channel_rq_msg)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:C_basic_frame_reflex_leave_channel_rq_msg_IsValidValue
                              extraTextFormatInfo:extraTextFormatInfo];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL C_basic_frame_reflex_leave_channel_rq_msg_IsValidValue(int32_t value__) {
  switch (value__) {
    case C_basic_frame_reflex_leave_channel_rq_msg_Id:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - C_basic_frame_reflex_leave_channel_rs

@implementation C_basic_frame_reflex_leave_channel_rs

@dynamic hasError, error;

typedef struct C_basic_frame_reflex_leave_channel_rs__storage_ {
  uint32_t _has_storage_[1];
  B_error_info *error;
} C_basic_frame_reflex_leave_channel_rs__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "error",
        .dataTypeSpecific.className = GPBStringifySymbol(B_error_info),
        .number = C_basic_frame_reflex_leave_channel_rs_FieldNumber_Error,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(C_basic_frame_reflex_leave_channel_rs__storage_, error),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[C_basic_frame_reflex_leave_channel_rs class]
                                     rootClass:[C_basic_frame_reflex_CBasicFrameReflexRoot class]
                                          file:C_basic_frame_reflex_CBasicFrameReflexRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(C_basic_frame_reflex_leave_channel_rs__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum C_basic_frame_reflex_leave_channel_rs_msg

GPBEnumDescriptor *C_basic_frame_reflex_leave_channel_rs_msg_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Id\000";
    static const int32_t values[] = {
        C_basic_frame_reflex_leave_channel_rs_msg_Id,
    };
    static const char *extraTextFormatInfo = "\001\000\"\000";
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(C_basic_frame_reflex_leave_channel_rs_msg)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:C_basic_frame_reflex_leave_channel_rs_msg_IsValidValue
                              extraTextFormatInfo:extraTextFormatInfo];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL C_basic_frame_reflex_leave_channel_rs_msg_IsValidValue(int32_t value__) {
  switch (value__) {
    case C_basic_frame_reflex_leave_channel_rs_msg_Id:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - C_basic_frame_reflex_simulation_frame_nt

@implementation C_basic_frame_reflex_simulation_frame_nt

@dynamic hasFrameNumber, frameNumber;
@dynamic variablesArray, variablesArray_Count;

typedef struct C_basic_frame_reflex_simulation_frame_nt__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *variablesArray;
  uint64_t frameNumber;
} C_basic_frame_reflex_simulation_frame_nt__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "frameNumber",
        .dataTypeSpecific.className = NULL,
        .number = C_basic_frame_reflex_simulation_frame_nt_FieldNumber_FrameNumber,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(C_basic_frame_reflex_simulation_frame_nt__storage_, frameNumber),
        .flags = (GPBFieldFlags)(GPBFieldRequired | GPBFieldHasDefaultValue),
        .dataType = GPBDataTypeUInt64,
      },
      {
        .name = "variablesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(C_basic_frame_reflex_simulation_variable),
        .number = C_basic_frame_reflex_simulation_frame_nt_FieldNumber_VariablesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(C_basic_frame_reflex_simulation_frame_nt__storage_, variablesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[C_basic_frame_reflex_simulation_frame_nt class]
                                     rootClass:[C_basic_frame_reflex_CBasicFrameReflexRoot class]
                                          file:C_basic_frame_reflex_CBasicFrameReflexRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(C_basic_frame_reflex_simulation_frame_nt__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - Enum C_basic_frame_reflex_simulation_frame_nt_msg

GPBEnumDescriptor *C_basic_frame_reflex_simulation_frame_nt_msg_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Id\000";
    static const int32_t values[] = {
        C_basic_frame_reflex_simulation_frame_nt_msg_Id,
    };
    static const char *extraTextFormatInfo = "\001\000\"\000";
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(C_basic_frame_reflex_simulation_frame_nt_msg)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:C_basic_frame_reflex_simulation_frame_nt_msg_IsValidValue
                              extraTextFormatInfo:extraTextFormatInfo];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL C_basic_frame_reflex_simulation_frame_nt_msg_IsValidValue(int32_t value__) {
  switch (value__) {
    case C_basic_frame_reflex_simulation_frame_nt_msg_Id:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
