// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: s_proxy_curl.proto

package protodef;

public final class s_proxy_curl {
  private s_proxy_curl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *&#47;///////////////////////////////////////////////////////////////
   * msg area.
   * </pre>
   *
   * Protobuf enum {@code s_proxy_curl.msg}
   */
  public enum msg
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>min_id = 16777472;</code>
     */
    min_id(16777472),
    /**
     * <code>max_id = 16777727;</code>
     */
    max_id(16777727),
    ;

    /**
     * <code>min_id = 16777472;</code>
     */
    public static final int min_id_VALUE = 16777472;
    /**
     * <code>max_id = 16777727;</code>
     */
    public static final int max_id_VALUE = 16777727;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static msg valueOf(int value) {
      return forNumber(value);
    }

    public static msg forNumber(int value) {
      switch (value) {
        case 16777472: return min_id;
        case 16777727: return max_id;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<msg>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        msg> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<msg>() {
            public msg findValueByNumber(int number) {
              return msg.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protodef.s_proxy_curl.getDescriptor().getEnumTypes().get(0);
    }

    private static final msg[] VALUES = values();

    public static msg valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private msg(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:s_proxy_curl.msg)
  }

  public interface json_data_rqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:s_proxy_curl.json_data_rq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * json buffer rq.
     * </pre>
     *
     * <code>required bytes buffer = 1;</code>
     */
    boolean hasBuffer();
    /**
     * <pre>
     * json buffer rq.
     * </pre>
     *
     * <code>required bytes buffer = 1;</code>
     */
    com.google.protobuf.ByteString getBuffer();
  }
  /**
   * <pre>
   *&#47;///////////////////////////////////////////////////////////////
   * struct
   * ////////////////////////////////////////////////////////////////
   * rq rs
   * set logger.
   * </pre>
   *
   * Protobuf type {@code s_proxy_curl.json_data_rq}
   */
  public  static final class json_data_rq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:s_proxy_curl.json_data_rq)
      json_data_rqOrBuilder {
    // Use json_data_rq.newBuilder() to construct.
    private json_data_rq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private json_data_rq() {
      buffer_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private json_data_rq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              buffer_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protodef.s_proxy_curl.internal_static_s_proxy_curl_json_data_rq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protodef.s_proxy_curl.internal_static_s_proxy_curl_json_data_rq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protodef.s_proxy_curl.json_data_rq.class, protodef.s_proxy_curl.json_data_rq.Builder.class);
    }

    /**
     * Protobuf enum {@code s_proxy_curl.json_data_rq.msg}
     */
    public enum msg
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>id = 16777472;</code>
       */
      id(16777472),
      ;

      /**
       * <code>id = 16777472;</code>
       */
      public static final int id_VALUE = 16777472;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static msg valueOf(int value) {
        return forNumber(value);
      }

      public static msg forNumber(int value) {
        switch (value) {
          case 16777472: return id;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<msg>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          msg> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<msg>() {
              public msg findValueByNumber(int number) {
                return msg.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protodef.s_proxy_curl.json_data_rq.getDescriptor().getEnumTypes().get(0);
      }

      private static final msg[] VALUES = values();

      public static msg valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private msg(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:s_proxy_curl.json_data_rq.msg)
    }

    private int bitField0_;
    public static final int BUFFER_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString buffer_;
    /**
     * <pre>
     * json buffer rq.
     * </pre>
     *
     * <code>required bytes buffer = 1;</code>
     */
    public boolean hasBuffer() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * json buffer rq.
     * </pre>
     *
     * <code>required bytes buffer = 1;</code>
     */
    public com.google.protobuf.ByteString getBuffer() {
      return buffer_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBuffer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, buffer_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, buffer_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protodef.s_proxy_curl.json_data_rq)) {
        return super.equals(obj);
      }
      protodef.s_proxy_curl.json_data_rq other = (protodef.s_proxy_curl.json_data_rq) obj;

      boolean result = true;
      result = result && (hasBuffer() == other.hasBuffer());
      if (hasBuffer()) {
        result = result && getBuffer()
            .equals(other.getBuffer());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBuffer()) {
        hash = (37 * hash) + BUFFER_FIELD_NUMBER;
        hash = (53 * hash) + getBuffer().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protodef.s_proxy_curl.json_data_rq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protodef.s_proxy_curl.json_data_rq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protodef.s_proxy_curl.json_data_rq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protodef.s_proxy_curl.json_data_rq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protodef.s_proxy_curl.json_data_rq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protodef.s_proxy_curl.json_data_rq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protodef.s_proxy_curl.json_data_rq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protodef.s_proxy_curl.json_data_rq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protodef.s_proxy_curl.json_data_rq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protodef.s_proxy_curl.json_data_rq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protodef.s_proxy_curl.json_data_rq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protodef.s_proxy_curl.json_data_rq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protodef.s_proxy_curl.json_data_rq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *&#47;///////////////////////////////////////////////////////////////
     * struct
     * ////////////////////////////////////////////////////////////////
     * rq rs
     * set logger.
     * </pre>
     *
     * Protobuf type {@code s_proxy_curl.json_data_rq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:s_proxy_curl.json_data_rq)
        protodef.s_proxy_curl.json_data_rqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protodef.s_proxy_curl.internal_static_s_proxy_curl_json_data_rq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protodef.s_proxy_curl.internal_static_s_proxy_curl_json_data_rq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protodef.s_proxy_curl.json_data_rq.class, protodef.s_proxy_curl.json_data_rq.Builder.class);
      }

      // Construct using protodef.s_proxy_curl.json_data_rq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        buffer_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protodef.s_proxy_curl.internal_static_s_proxy_curl_json_data_rq_descriptor;
      }

      public protodef.s_proxy_curl.json_data_rq getDefaultInstanceForType() {
        return protodef.s_proxy_curl.json_data_rq.getDefaultInstance();
      }

      public protodef.s_proxy_curl.json_data_rq build() {
        protodef.s_proxy_curl.json_data_rq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protodef.s_proxy_curl.json_data_rq buildPartial() {
        protodef.s_proxy_curl.json_data_rq result = new protodef.s_proxy_curl.json_data_rq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.buffer_ = buffer_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protodef.s_proxy_curl.json_data_rq) {
          return mergeFrom((protodef.s_proxy_curl.json_data_rq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protodef.s_proxy_curl.json_data_rq other) {
        if (other == protodef.s_proxy_curl.json_data_rq.getDefaultInstance()) return this;
        if (other.hasBuffer()) {
          setBuffer(other.getBuffer());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBuffer()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protodef.s_proxy_curl.json_data_rq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protodef.s_proxy_curl.json_data_rq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString buffer_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * json buffer rq.
       * </pre>
       *
       * <code>required bytes buffer = 1;</code>
       */
      public boolean hasBuffer() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * json buffer rq.
       * </pre>
       *
       * <code>required bytes buffer = 1;</code>
       */
      public com.google.protobuf.ByteString getBuffer() {
        return buffer_;
      }
      /**
       * <pre>
       * json buffer rq.
       * </pre>
       *
       * <code>required bytes buffer = 1;</code>
       */
      public Builder setBuffer(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        buffer_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * json buffer rq.
       * </pre>
       *
       * <code>required bytes buffer = 1;</code>
       */
      public Builder clearBuffer() {
        bitField0_ = (bitField0_ & ~0x00000001);
        buffer_ = getDefaultInstance().getBuffer();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:s_proxy_curl.json_data_rq)
    }

    // @@protoc_insertion_point(class_scope:s_proxy_curl.json_data_rq)
    private static final protodef.s_proxy_curl.json_data_rq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protodef.s_proxy_curl.json_data_rq();
    }

    public static protodef.s_proxy_curl.json_data_rq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<json_data_rq>
        PARSER = new com.google.protobuf.AbstractParser<json_data_rq>() {
      public json_data_rq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new json_data_rq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<json_data_rq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<json_data_rq> getParserForType() {
      return PARSER;
    }

    public protodef.s_proxy_curl.json_data_rq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface json_data_rsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:s_proxy_curl.json_data_rs)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * error info
     * </pre>
     *
     * <code>required .b_error.info error = 1;</code>
     */
    boolean hasError();
    /**
     * <pre>
     * error info
     * </pre>
     *
     * <code>required .b_error.info error = 1;</code>
     */
    protodef.b_error.info getError();
    /**
     * <pre>
     * error info
     * </pre>
     *
     * <code>required .b_error.info error = 1;</code>
     */
    protodef.b_error.infoOrBuilder getErrorOrBuilder();

    /**
     * <pre>
     * curl code.
     * </pre>
     *
     * <code>required uint32 curl_code = 2 [default = 0];</code>
     */
    boolean hasCurlCode();
    /**
     * <pre>
     * curl code.
     * </pre>
     *
     * <code>required uint32 curl_code = 2 [default = 0];</code>
     */
    int getCurlCode();

    /**
     * <pre>
     * json buffer rs.
     * </pre>
     *
     * <code>required bytes buffer = 3;</code>
     */
    boolean hasBuffer();
    /**
     * <pre>
     * json buffer rs.
     * </pre>
     *
     * <code>required bytes buffer = 3;</code>
     */
    com.google.protobuf.ByteString getBuffer();
  }
  /**
   * Protobuf type {@code s_proxy_curl.json_data_rs}
   */
  public  static final class json_data_rs extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:s_proxy_curl.json_data_rs)
      json_data_rsOrBuilder {
    // Use json_data_rs.newBuilder() to construct.
    private json_data_rs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private json_data_rs() {
      curlCode_ = 0;
      buffer_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private json_data_rs(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              protodef.b_error.info.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = error_.toBuilder();
              }
              error_ = input.readMessage(protodef.b_error.info.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(error_);
                error_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              curlCode_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              buffer_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protodef.s_proxy_curl.internal_static_s_proxy_curl_json_data_rs_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protodef.s_proxy_curl.internal_static_s_proxy_curl_json_data_rs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protodef.s_proxy_curl.json_data_rs.class, protodef.s_proxy_curl.json_data_rs.Builder.class);
    }

    /**
     * Protobuf enum {@code s_proxy_curl.json_data_rs.msg}
     */
    public enum msg
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>id = 16777473;</code>
       */
      id(16777473),
      ;

      /**
       * <code>id = 16777473;</code>
       */
      public static final int id_VALUE = 16777473;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static msg valueOf(int value) {
        return forNumber(value);
      }

      public static msg forNumber(int value) {
        switch (value) {
          case 16777473: return id;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<msg>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          msg> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<msg>() {
              public msg findValueByNumber(int number) {
                return msg.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protodef.s_proxy_curl.json_data_rs.getDescriptor().getEnumTypes().get(0);
      }

      private static final msg[] VALUES = values();

      public static msg valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private msg(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:s_proxy_curl.json_data_rs.msg)
    }

    private int bitField0_;
    public static final int ERROR_FIELD_NUMBER = 1;
    private protodef.b_error.info error_;
    /**
     * <pre>
     * error info
     * </pre>
     *
     * <code>required .b_error.info error = 1;</code>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * error info
     * </pre>
     *
     * <code>required .b_error.info error = 1;</code>
     */
    public protodef.b_error.info getError() {
      return error_ == null ? protodef.b_error.info.getDefaultInstance() : error_;
    }
    /**
     * <pre>
     * error info
     * </pre>
     *
     * <code>required .b_error.info error = 1;</code>
     */
    public protodef.b_error.infoOrBuilder getErrorOrBuilder() {
      return error_ == null ? protodef.b_error.info.getDefaultInstance() : error_;
    }

    public static final int CURL_CODE_FIELD_NUMBER = 2;
    private int curlCode_;
    /**
     * <pre>
     * curl code.
     * </pre>
     *
     * <code>required uint32 curl_code = 2 [default = 0];</code>
     */
    public boolean hasCurlCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * curl code.
     * </pre>
     *
     * <code>required uint32 curl_code = 2 [default = 0];</code>
     */
    public int getCurlCode() {
      return curlCode_;
    }

    public static final int BUFFER_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString buffer_;
    /**
     * <pre>
     * json buffer rs.
     * </pre>
     *
     * <code>required bytes buffer = 3;</code>
     */
    public boolean hasBuffer() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * json buffer rs.
     * </pre>
     *
     * <code>required bytes buffer = 3;</code>
     */
    public com.google.protobuf.ByteString getBuffer() {
      return buffer_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasError()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCurlCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBuffer()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getError().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getError());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, curlCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, buffer_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getError());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, curlCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, buffer_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protodef.s_proxy_curl.json_data_rs)) {
        return super.equals(obj);
      }
      protodef.s_proxy_curl.json_data_rs other = (protodef.s_proxy_curl.json_data_rs) obj;

      boolean result = true;
      result = result && (hasError() == other.hasError());
      if (hasError()) {
        result = result && getError()
            .equals(other.getError());
      }
      result = result && (hasCurlCode() == other.hasCurlCode());
      if (hasCurlCode()) {
        result = result && (getCurlCode()
            == other.getCurlCode());
      }
      result = result && (hasBuffer() == other.hasBuffer());
      if (hasBuffer()) {
        result = result && getBuffer()
            .equals(other.getBuffer());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasError()) {
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getError().hashCode();
      }
      if (hasCurlCode()) {
        hash = (37 * hash) + CURL_CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCurlCode();
      }
      if (hasBuffer()) {
        hash = (37 * hash) + BUFFER_FIELD_NUMBER;
        hash = (53 * hash) + getBuffer().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protodef.s_proxy_curl.json_data_rs parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protodef.s_proxy_curl.json_data_rs parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protodef.s_proxy_curl.json_data_rs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protodef.s_proxy_curl.json_data_rs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protodef.s_proxy_curl.json_data_rs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protodef.s_proxy_curl.json_data_rs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protodef.s_proxy_curl.json_data_rs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protodef.s_proxy_curl.json_data_rs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protodef.s_proxy_curl.json_data_rs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protodef.s_proxy_curl.json_data_rs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protodef.s_proxy_curl.json_data_rs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protodef.s_proxy_curl.json_data_rs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protodef.s_proxy_curl.json_data_rs prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code s_proxy_curl.json_data_rs}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:s_proxy_curl.json_data_rs)
        protodef.s_proxy_curl.json_data_rsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protodef.s_proxy_curl.internal_static_s_proxy_curl_json_data_rs_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protodef.s_proxy_curl.internal_static_s_proxy_curl_json_data_rs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protodef.s_proxy_curl.json_data_rs.class, protodef.s_proxy_curl.json_data_rs.Builder.class);
      }

      // Construct using protodef.s_proxy_curl.json_data_rs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getErrorFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (errorBuilder_ == null) {
          error_ = null;
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        curlCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        buffer_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protodef.s_proxy_curl.internal_static_s_proxy_curl_json_data_rs_descriptor;
      }

      public protodef.s_proxy_curl.json_data_rs getDefaultInstanceForType() {
        return protodef.s_proxy_curl.json_data_rs.getDefaultInstance();
      }

      public protodef.s_proxy_curl.json_data_rs build() {
        protodef.s_proxy_curl.json_data_rs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protodef.s_proxy_curl.json_data_rs buildPartial() {
        protodef.s_proxy_curl.json_data_rs result = new protodef.s_proxy_curl.json_data_rs(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (errorBuilder_ == null) {
          result.error_ = error_;
        } else {
          result.error_ = errorBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.curlCode_ = curlCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.buffer_ = buffer_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protodef.s_proxy_curl.json_data_rs) {
          return mergeFrom((protodef.s_proxy_curl.json_data_rs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protodef.s_proxy_curl.json_data_rs other) {
        if (other == protodef.s_proxy_curl.json_data_rs.getDefaultInstance()) return this;
        if (other.hasError()) {
          mergeError(other.getError());
        }
        if (other.hasCurlCode()) {
          setCurlCode(other.getCurlCode());
        }
        if (other.hasBuffer()) {
          setBuffer(other.getBuffer());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasError()) {
          return false;
        }
        if (!hasCurlCode()) {
          return false;
        }
        if (!hasBuffer()) {
          return false;
        }
        if (!getError().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protodef.s_proxy_curl.json_data_rs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protodef.s_proxy_curl.json_data_rs) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private protodef.b_error.info error_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          protodef.b_error.info, protodef.b_error.info.Builder, protodef.b_error.infoOrBuilder> errorBuilder_;
      /**
       * <pre>
       * error info
       * </pre>
       *
       * <code>required .b_error.info error = 1;</code>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * error info
       * </pre>
       *
       * <code>required .b_error.info error = 1;</code>
       */
      public protodef.b_error.info getError() {
        if (errorBuilder_ == null) {
          return error_ == null ? protodef.b_error.info.getDefaultInstance() : error_;
        } else {
          return errorBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * error info
       * </pre>
       *
       * <code>required .b_error.info error = 1;</code>
       */
      public Builder setError(protodef.b_error.info value) {
        if (errorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          error_ = value;
          onChanged();
        } else {
          errorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * error info
       * </pre>
       *
       * <code>required .b_error.info error = 1;</code>
       */
      public Builder setError(
          protodef.b_error.info.Builder builderForValue) {
        if (errorBuilder_ == null) {
          error_ = builderForValue.build();
          onChanged();
        } else {
          errorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * error info
       * </pre>
       *
       * <code>required .b_error.info error = 1;</code>
       */
      public Builder mergeError(protodef.b_error.info value) {
        if (errorBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              error_ != null &&
              error_ != protodef.b_error.info.getDefaultInstance()) {
            error_ =
              protodef.b_error.info.newBuilder(error_).mergeFrom(value).buildPartial();
          } else {
            error_ = value;
          }
          onChanged();
        } else {
          errorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       * error info
       * </pre>
       *
       * <code>required .b_error.info error = 1;</code>
       */
      public Builder clearError() {
        if (errorBuilder_ == null) {
          error_ = null;
          onChanged();
        } else {
          errorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <pre>
       * error info
       * </pre>
       *
       * <code>required .b_error.info error = 1;</code>
       */
      public protodef.b_error.info.Builder getErrorBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getErrorFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * error info
       * </pre>
       *
       * <code>required .b_error.info error = 1;</code>
       */
      public protodef.b_error.infoOrBuilder getErrorOrBuilder() {
        if (errorBuilder_ != null) {
          return errorBuilder_.getMessageOrBuilder();
        } else {
          return error_ == null ?
              protodef.b_error.info.getDefaultInstance() : error_;
        }
      }
      /**
       * <pre>
       * error info
       * </pre>
       *
       * <code>required .b_error.info error = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protodef.b_error.info, protodef.b_error.info.Builder, protodef.b_error.infoOrBuilder> 
          getErrorFieldBuilder() {
        if (errorBuilder_ == null) {
          errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protodef.b_error.info, protodef.b_error.info.Builder, protodef.b_error.infoOrBuilder>(
                  getError(),
                  getParentForChildren(),
                  isClean());
          error_ = null;
        }
        return errorBuilder_;
      }

      private int curlCode_ ;
      /**
       * <pre>
       * curl code.
       * </pre>
       *
       * <code>required uint32 curl_code = 2 [default = 0];</code>
       */
      public boolean hasCurlCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * curl code.
       * </pre>
       *
       * <code>required uint32 curl_code = 2 [default = 0];</code>
       */
      public int getCurlCode() {
        return curlCode_;
      }
      /**
       * <pre>
       * curl code.
       * </pre>
       *
       * <code>required uint32 curl_code = 2 [default = 0];</code>
       */
      public Builder setCurlCode(int value) {
        bitField0_ |= 0x00000002;
        curlCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * curl code.
       * </pre>
       *
       * <code>required uint32 curl_code = 2 [default = 0];</code>
       */
      public Builder clearCurlCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        curlCode_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString buffer_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * json buffer rs.
       * </pre>
       *
       * <code>required bytes buffer = 3;</code>
       */
      public boolean hasBuffer() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * json buffer rs.
       * </pre>
       *
       * <code>required bytes buffer = 3;</code>
       */
      public com.google.protobuf.ByteString getBuffer() {
        return buffer_;
      }
      /**
       * <pre>
       * json buffer rs.
       * </pre>
       *
       * <code>required bytes buffer = 3;</code>
       */
      public Builder setBuffer(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        buffer_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * json buffer rs.
       * </pre>
       *
       * <code>required bytes buffer = 3;</code>
       */
      public Builder clearBuffer() {
        bitField0_ = (bitField0_ & ~0x00000004);
        buffer_ = getDefaultInstance().getBuffer();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:s_proxy_curl.json_data_rs)
    }

    // @@protoc_insertion_point(class_scope:s_proxy_curl.json_data_rs)
    private static final protodef.s_proxy_curl.json_data_rs DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protodef.s_proxy_curl.json_data_rs();
    }

    public static protodef.s_proxy_curl.json_data_rs getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<json_data_rs>
        PARSER = new com.google.protobuf.AbstractParser<json_data_rs>() {
      public json_data_rs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new json_data_rs(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<json_data_rs> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<json_data_rs> getParserForType() {
      return PARSER;
    }

    public protodef.s_proxy_curl.json_data_rs getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_s_proxy_curl_json_data_rq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_s_proxy_curl_json_data_rq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_s_proxy_curl_json_data_rs_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_s_proxy_curl_json_data_rs_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022s_proxy_curl.proto\022\014s_proxy_curl\032\rb_er" +
      "ror.proto\"0\n\014json_data_rq\022\016\n\006buffer\030\001 \002(" +
      "\014\"\020\n\003msg\022\t\n\002id\020\200\202\200\010\"d\n\014json_data_rs\022\034\n\005e" +
      "rror\030\001 \002(\0132\r.b_error.info\022\024\n\tcurl_code\030\002" +
      " \002(\r:\0010\022\016\n\006buffer\030\003 \002(\014\"\020\n\003msg\022\t\n\002id\020\201\202\200" +
      "\010*#\n\003msg\022\r\n\006min_id\020\200\202\200\010\022\r\n\006max_id\020\377\203\200\010BN" +
      "\n\010protodefB\014s_proxy_curlZ\025protodef/s_pro" +
      "xy_curl\242\002\rS_proxy_curl_\252\002\014s_proxy_curl"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protodef.b_error.getDescriptor(),
        }, assigner);
    internal_static_s_proxy_curl_json_data_rq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_s_proxy_curl_json_data_rq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_s_proxy_curl_json_data_rq_descriptor,
        new java.lang.String[] { "Buffer", });
    internal_static_s_proxy_curl_json_data_rs_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_s_proxy_curl_json_data_rs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_s_proxy_curl_json_data_rs_descriptor,
        new java.lang.String[] { "Error", "CurlCode", "Buffer", });
    protodef.b_error.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
