// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: b_business_relation.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "BBusinessRelation.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - B_business_relation_BBusinessRelationRoot

@implementation B_business_relation_BBusinessRelationRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - B_business_relation_BBusinessRelationRoot_FileDescriptor

static GPBFileDescriptor *B_business_relation_BBusinessRelationRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"b_business_relation"
                                                 objcPrefix:@"B_business_relation_"
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - B_business_relation_user_relation

@implementation B_business_relation_user_relation

@dynamic hasUserId, userId;
@dynamic hasFriendGroupId, friendGroupId;
@dynamic hasFriendId, friendId;
@dynamic hasFriendRemark, friendRemark;
@dynamic hasBuildFriendTime, buildFriendTime;

typedef struct B_business_relation_user_relation__storage_ {
  uint32_t _has_storage_[1];
  uint32_t buildFriendTime;
  NSString *friendRemark;
  uint64_t userId;
  uint64_t friendGroupId;
  uint64_t friendId;
} B_business_relation_user_relation__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = B_business_relation_user_relation_FieldNumber_UserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(B_business_relation_user_relation__storage_, userId),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeUInt64,
      },
      {
        .name = "friendGroupId",
        .dataTypeSpecific.className = NULL,
        .number = B_business_relation_user_relation_FieldNumber_FriendGroupId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(B_business_relation_user_relation__storage_, friendGroupId),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeUInt64,
      },
      {
        .name = "friendId",
        .dataTypeSpecific.className = NULL,
        .number = B_business_relation_user_relation_FieldNumber_FriendId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(B_business_relation_user_relation__storage_, friendId),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeUInt64,
      },
      {
        .name = "friendRemark",
        .dataTypeSpecific.className = NULL,
        .number = B_business_relation_user_relation_FieldNumber_FriendRemark,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(B_business_relation_user_relation__storage_, friendRemark),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "buildFriendTime",
        .dataTypeSpecific.className = NULL,
        .number = B_business_relation_user_relation_FieldNumber_BuildFriendTime,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(B_business_relation_user_relation__storage_, buildFriendTime),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeUInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[B_business_relation_user_relation class]
                                     rootClass:[B_business_relation_BBusinessRelationRoot class]
                                          file:B_business_relation_BBusinessRelationRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(B_business_relation_user_relation__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - B_business_relation_user_relation_group

@implementation B_business_relation_user_relation_group

@dynamic hasId_p, id_p;
@dynamic hasUserId, userId;
@dynamic hasFriendGroup, friendGroup;

typedef struct B_business_relation_user_relation_group__storage_ {
  uint32_t _has_storage_[1];
  NSString *friendGroup;
  uint64_t id_p;
  uint64_t userId;
} B_business_relation_user_relation_group__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = B_business_relation_user_relation_group_FieldNumber_Id_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(B_business_relation_user_relation_group__storage_, id_p),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeUInt64,
      },
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = B_business_relation_user_relation_group_FieldNumber_UserId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(B_business_relation_user_relation_group__storage_, userId),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeUInt64,
      },
      {
        .name = "friendGroup",
        .dataTypeSpecific.className = NULL,
        .number = B_business_relation_user_relation_group_FieldNumber_FriendGroup,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(B_business_relation_user_relation_group__storage_, friendGroup),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[B_business_relation_user_relation_group class]
                                     rootClass:[B_business_relation_BBusinessRelationRoot class]
                                          file:B_business_relation_BBusinessRelationRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(B_business_relation_user_relation_group__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - B_business_relation_friend_apply

@implementation B_business_relation_friend_apply

@dynamic hasUserApplyId, userApplyId;
@dynamic hasUserApplyName, userApplyName;
@dynamic hasUserApplyNick, userApplyNick;
@dynamic hasUserApplyCreateTime, userApplyCreateTime;
@dynamic hasUserApplyDescription, userApplyDescription;

typedef struct B_business_relation_friend_apply__storage_ {
  uint32_t _has_storage_[1];
  uint32_t userApplyCreateTime;
  NSString *userApplyName;
  NSString *userApplyNick;
  NSString *userApplyDescription;
  uint64_t userApplyId;
} B_business_relation_friend_apply__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userApplyId",
        .dataTypeSpecific.className = NULL,
        .number = B_business_relation_friend_apply_FieldNumber_UserApplyId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(B_business_relation_friend_apply__storage_, userApplyId),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeUInt64,
      },
      {
        .name = "userApplyName",
        .dataTypeSpecific.className = NULL,
        .number = B_business_relation_friend_apply_FieldNumber_UserApplyName,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(B_business_relation_friend_apply__storage_, userApplyName),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userApplyNick",
        .dataTypeSpecific.className = NULL,
        .number = B_business_relation_friend_apply_FieldNumber_UserApplyNick,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(B_business_relation_friend_apply__storage_, userApplyNick),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userApplyCreateTime",
        .dataTypeSpecific.className = NULL,
        .number = B_business_relation_friend_apply_FieldNumber_UserApplyCreateTime,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(B_business_relation_friend_apply__storage_, userApplyCreateTime),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "userApplyDescription",
        .dataTypeSpecific.className = NULL,
        .number = B_business_relation_friend_apply_FieldNumber_UserApplyDescription,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(B_business_relation_friend_apply__storage_, userApplyDescription),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[B_business_relation_friend_apply class]
                                     rootClass:[B_business_relation_BBusinessRelationRoot class]
                                          file:B_business_relation_BBusinessRelationRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(B_business_relation_friend_apply__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
