// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: s_shuttle_lobby.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class B_math_coord;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum S_shuttle_lobby_msg

typedef GPB_ENUM(S_shuttle_lobby_msg) {
  S_shuttle_lobby_msg_MinId = 16781568,
  S_shuttle_lobby_msg_MaxId = 16781823,
};

GPBEnumDescriptor *S_shuttle_lobby_msg_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL S_shuttle_lobby_msg_IsValidValue(int32_t value);

#pragma mark - Enum S_shuttle_lobby_token_verify_ev_msg

typedef GPB_ENUM(S_shuttle_lobby_token_verify_ev_msg) {
  S_shuttle_lobby_token_verify_ev_msg_Id = 16781569,
};

GPBEnumDescriptor *S_shuttle_lobby_token_verify_ev_msg_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL S_shuttle_lobby_token_verify_ev_msg_IsValidValue(int32_t value);

#pragma mark - Enum S_shuttle_lobby_heartbeat_ev_msg

typedef GPB_ENUM(S_shuttle_lobby_heartbeat_ev_msg) {
  S_shuttle_lobby_heartbeat_ev_msg_Id = 16781570,
};

GPBEnumDescriptor *S_shuttle_lobby_heartbeat_ev_msg_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL S_shuttle_lobby_heartbeat_ev_msg_IsValidValue(int32_t value);

#pragma mark - S_shuttle_lobby_SShuttleLobbyRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface S_shuttle_lobby_SShuttleLobbyRoot : GPBRootObject
@end

#pragma mark - S_shuttle_lobby_token_verify_ev

typedef GPB_ENUM(S_shuttle_lobby_token_verify_ev_FieldNumber) {
  S_shuttle_lobby_token_verify_ev_FieldNumber_EventTime = 1,
  S_shuttle_lobby_token_verify_ev_FieldNumber_Uid = 2,
  S_shuttle_lobby_token_verify_ev_FieldNumber_SidNow = 3,
  S_shuttle_lobby_token_verify_ev_FieldNumber_SidOld = 4,
};

/**
 * (tcp)令牌校验事件.
 **/
@interface S_shuttle_lobby_token_verify_ev : GPBMessage

/** 事件发生时间戳(毫秒) */
@property(nonatomic, readwrite) uint64_t eventTime;

@property(nonatomic, readwrite) BOOL hasEventTime;
/** 用户编号 */
@property(nonatomic, readwrite) uint64_t uid;

@property(nonatomic, readwrite) BOOL hasUid;
/** 当前添加用户会话号 */
@property(nonatomic, readwrite) uint64_t sidNow;

@property(nonatomic, readwrite) BOOL hasSidNow;
/** 被踢掉的用户会话号 */
@property(nonatomic, readwrite) uint64_t sidOld;

@property(nonatomic, readwrite) BOOL hasSidOld;
@end

#pragma mark - S_shuttle_lobby_heartbeat_ev

typedef GPB_ENUM(S_shuttle_lobby_heartbeat_ev_FieldNumber) {
  S_shuttle_lobby_heartbeat_ev_FieldNumber_EventTime = 1,
  S_shuttle_lobby_heartbeat_ev_FieldNumber_Uid = 2,
  S_shuttle_lobby_heartbeat_ev_FieldNumber_TimecodeNative = 3,
  S_shuttle_lobby_heartbeat_ev_FieldNumber_CoordInfo = 4,
};

/**
 * (tcp)大厅心跳事件
 **/
@interface S_shuttle_lobby_heartbeat_ev : GPBMessage

/** 事件发生时间戳(毫秒) */
@property(nonatomic, readwrite) uint64_t eventTime;

@property(nonatomic, readwrite) BOOL hasEventTime;
/** 用户编号 */
@property(nonatomic, readwrite) uint64_t uid;

@property(nonatomic, readwrite) BOOL hasUid;
/** 发出的时间点(ms毫秒) */
@property(nonatomic, readwrite) uint64_t timecodeNative;

@property(nonatomic, readwrite) BOOL hasTimecodeNative;
/** Earth(j,w). */
@property(nonatomic, readwrite, strong, null_resettable) B_math_coord *coordInfo;
/** Test to see if @c coordInfo has been set. */
@property(nonatomic, readwrite) BOOL hasCoordInfo;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
