# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: b_math.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='b_math.proto',
  package='b_math',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x62_math.proto\x12\x06\x62_math\"#\n\x05\x63oord\x12\x0c\n\x01j\x18\x01 \x02(\x01:\x01\x30\x12\x0c\n\x01w\x18\x02 \x02(\x01:\x01\x30\"\"\n\x04vec2\x12\x0c\n\x01x\x18\x01 \x02(\x01:\x01\x30\x12\x0c\n\x01y\x18\x02 \x02(\x01:\x01\x30\"0\n\x04vec3\x12\x0c\n\x01x\x18\x01 \x02(\x01:\x01\x30\x12\x0c\n\x01y\x18\x02 \x02(\x01:\x01\x30\x12\x0c\n\x01z\x18\x03 \x02(\x01:\x01\x30\">\n\x04vec4\x12\x0c\n\x01x\x18\x01 \x02(\x01:\x01\x30\x12\x0c\n\x01y\x18\x02 \x02(\x01:\x01\x30\x12\x0c\n\x01z\x18\x03 \x02(\x01:\x01\x30\x12\x0c\n\x01w\x18\x04 \x02(\x01:\x01\x30\"\x11\n\x04mat3\x12\t\n\x01m\x18\x01 \x03(\x01\"\x11\n\x04mat4\x12\t\n\x01m\x18\x01 \x03(\x01\x42\x36\n\x08protodefB\x06\x62_mathZ\x0fprotodef/b_math\xa2\x02\x07\x42_math_\xaa\x02\x06\x62_math')
)




_COORD = _descriptor.Descriptor(
  name='coord',
  full_name='b_math.coord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='j', full_name='b_math.coord.j', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w', full_name='b_math.coord.w', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=59,
)


_VEC2 = _descriptor.Descriptor(
  name='vec2',
  full_name='b_math.vec2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='b_math.vec2.x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='b_math.vec2.y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=95,
)


_VEC3 = _descriptor.Descriptor(
  name='vec3',
  full_name='b_math.vec3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='b_math.vec3.x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='b_math.vec3.y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='b_math.vec3.z', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=145,
)


_VEC4 = _descriptor.Descriptor(
  name='vec4',
  full_name='b_math.vec4',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='b_math.vec4.x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='b_math.vec4.y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='b_math.vec4.z', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w', full_name='b_math.vec4.w', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=209,
)


_MAT3 = _descriptor.Descriptor(
  name='mat3',
  full_name='b_math.mat3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m', full_name='b_math.mat3.m', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=228,
)


_MAT4 = _descriptor.Descriptor(
  name='mat4',
  full_name='b_math.mat4',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m', full_name='b_math.mat4.m', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=247,
)

DESCRIPTOR.message_types_by_name['coord'] = _COORD
DESCRIPTOR.message_types_by_name['vec2'] = _VEC2
DESCRIPTOR.message_types_by_name['vec3'] = _VEC3
DESCRIPTOR.message_types_by_name['vec4'] = _VEC4
DESCRIPTOR.message_types_by_name['mat3'] = _MAT3
DESCRIPTOR.message_types_by_name['mat4'] = _MAT4
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

coord = _reflection.GeneratedProtocolMessageType('coord', (_message.Message,), dict(
  DESCRIPTOR = _COORD,
  __module__ = 'b_math_pb2'
  # @@protoc_insertion_point(class_scope:b_math.coord)
  ))
_sym_db.RegisterMessage(coord)

vec2 = _reflection.GeneratedProtocolMessageType('vec2', (_message.Message,), dict(
  DESCRIPTOR = _VEC2,
  __module__ = 'b_math_pb2'
  # @@protoc_insertion_point(class_scope:b_math.vec2)
  ))
_sym_db.RegisterMessage(vec2)

vec3 = _reflection.GeneratedProtocolMessageType('vec3', (_message.Message,), dict(
  DESCRIPTOR = _VEC3,
  __module__ = 'b_math_pb2'
  # @@protoc_insertion_point(class_scope:b_math.vec3)
  ))
_sym_db.RegisterMessage(vec3)

vec4 = _reflection.GeneratedProtocolMessageType('vec4', (_message.Message,), dict(
  DESCRIPTOR = _VEC4,
  __module__ = 'b_math_pb2'
  # @@protoc_insertion_point(class_scope:b_math.vec4)
  ))
_sym_db.RegisterMessage(vec4)

mat3 = _reflection.GeneratedProtocolMessageType('mat3', (_message.Message,), dict(
  DESCRIPTOR = _MAT3,
  __module__ = 'b_math_pb2'
  # @@protoc_insertion_point(class_scope:b_math.mat3)
  ))
_sym_db.RegisterMessage(mat3)

mat4 = _reflection.GeneratedProtocolMessageType('mat4', (_message.Message,), dict(
  DESCRIPTOR = _MAT4,
  __module__ = 'b_math_pb2'
  # @@protoc_insertion_point(class_scope:b_math.mat4)
  ))
_sym_db.RegisterMessage(mat4)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\010protodefB\006b_mathZ\017protodef/b_math\242\002\007B_math_\252\002\006b_math'))
# @@protoc_insertion_point(module_scope)
